import {QuestionApiError} from "./questions";

export type PublicTanidik={id:string;name:string;activeTanidik:boolean;educationVerified:boolean;educationStatus:string|null;universityName:string|null;departmentName:string|null;classYear:number|null;graduationYear:number|null;biography:string|null;occupation:string|null;company:string|null;linkedinUrl:string|null;portfolioUrl:string|null;avatarFileId:string|null;tanidikAnswerCount:number;communityAnswerCount:number;helpfulVoteCount:number;bestAnswerCount:number;helpedPeopleCount:number;createdAt:string};
export type TanidikPage={items:PublicTanidik[];page:number;size:number;totalElements:number};
const nullable=(value:unknown)=>typeof value==="string"||value===null;
const valid=(value:unknown):value is PublicTanidik=>{if(typeof value!=="object"||value===null)return false;const p=value as Record<string,unknown>;return typeof p.id==="string"&&typeof p.name==="string"&&typeof p.activeTanidik==="boolean"&&typeof p.educationVerified==="boolean"&&nullable(p.educationStatus)&&nullable(p.universityName)&&nullable(p.departmentName)&&(typeof p.classYear==="number"||p.classYear===null)&&(typeof p.graduationYear==="number"||p.graduationYear===null)&&nullable(p.biography)&&nullable(p.occupation)&&nullable(p.company)&&nullable(p.linkedinUrl)&&nullable(p.portfolioUrl)&&nullable(p.avatarFileId)&&[p.tanidikAnswerCount,p.communityAnswerCount,p.helpfulVoteCount,p.bestAnswerCount,p.helpedPeopleCount].every(item=>typeof item==="number")&&typeof p.createdAt==="string";};
async function json(path:string){let response:Response;try{response=await fetch(new URL(path,process.env.API_BASE_URL??"http://localhost:8080"),{cache:"no-store",headers:{Accept:"application/json"}});}catch{throw new QuestionApiError("Tanıdık profillerine ulaşılamıyor.");}if(!response.ok)throw new QuestionApiError("Tanıdık profili yüklenemedi.",response.status);return response.json() as Promise<unknown>;}
export async function getTanidik(id:string){const payload=await json(`/api/tanidiklar/${id}`);if(!valid(payload))throw new QuestionApiError("Tanıdık profili beklenmeyen yanıt döndürdü.");return {...payload,role:"TANIDIK" as const};}
export async function getTanidiklar(q="",page=0,filters:{universityId?:string;departmentId?:string;educationStatus?:string;classYear?:number;verified?:boolean;expertise?:string;size?:number}={}){const params=new URLSearchParams({q,page:String(page),size:String(filters.size??20)});Object.entries(filters).forEach(([key,value])=>{if(key!=="size"&&value!==undefined&&value!=="")params.set(key,String(value));});const payload=await json(`/api/tanidiklar?${params}`);if(typeof payload!=="object"||payload===null)throw new QuestionApiError("Tanıdık listesi beklenmeyen yanıt döndürdü.");const result=payload as Record<string,unknown>;if(!Array.isArray(result.items)||!result.items.every(valid)||typeof result.page!=="number"||typeof result.size!=="number"||typeof result.totalElements!=="number")throw new QuestionApiError("Tanıdık listesi beklenmeyen yanıt döndürdü.");return result as TanidikPage;}
