import Link from "next/link";
import {notFound} from "next/navigation";
import {getProfileAnswers} from "@/lib/api/answers";
import {questionSegment} from "@/lib/public-url";
import {plainProgramName} from "@/lib/program-label";
import {ProfileIdentityCard} from "@/components/profile-identity-card";
import {getProfileContributionSummary} from "@/lib/api/profile-contributions";

type Profile={id:string;name:string;role:string;educationStatus:string|null;universityName:string|null;departmentName:string|null;graduationYear:number|null;biography:string|null;occupation:string|null;company:string|null;linkedinUrl:string|null;portfolioUrl:string|null;createdAt:string};
async function profile(id:string){const response=await fetch(new URL(`/api/profiles/${id}`,process.env.API_BASE_URL??"http://localhost:8080"),{cache:"no-store"});if(!response.ok)notFound();return response.json() as Promise<Profile>;}
export default async function PublicMemberProfile({params}:{params:Promise<{profileId:string}>}){const data=await profile((await params).profileId),[answers,contributionSummary]=await Promise.all([getProfileAnswers(data.id),getProfileContributionSummary(data.id)]);return <article className="legacy-public-profile"><nav className="breadcrumb"><Link href="/sorular">Sorular</Link><span>›</span><span>{data.name}</span></nav><ProfileIdentityCard name={data.name} profileId={data.id} educationStatus={data.educationStatus} subtitle={[data.universityName,plainProgramName(data.departmentName)].filter(Boolean).join(" · ")} biography={data.biography} contributionSummary={contributionSummary} facts={[{label:"Şirket",value:data.company},{label:"Meslek",value:data.occupation},{label:"Mezuniyet yılı",value:data.graduationYear},{label:"Hesap açılışı",value:new Intl.DateTimeFormat("tr-TR",{dateStyle:"long",timeZone:"Europe/Istanbul"}).format(new Date(data.createdAt))}]} links={[...(data.linkedinUrl?[{label:"LinkedIn",href:data.linkedinUrl}]:[]),...(data.portfolioUrl?[{label:"Portfolyo",href:data.portfolioUrl}]:[])]}/><section className="legacy-profile-contributions"><h2>Katkılar</h2>{answers.length?<ol className="legacy-profile-answer-list">{answers.map(answer=><li key={answer.id}><p>{answer.body}</p><footer><time dateTime={answer.publishedAt}>{new Intl.DateTimeFormat("tr-TR",{dateStyle:"medium",timeZone:"Europe/Istanbul"}).format(new Date(answer.publishedAt))}</time><Link href={`/soru/${questionSegment(answer.questionTitle??"soru",answer.questionId)}`}>Soru detayı</Link></footer></li>)}</ol>:<div className="empty-state"><h3>Henüz katkı yok</h3></div>}</section></article>}
