import {getDecisionData,type Category} from "@/lib/api/decisions";
import {currentUser} from "@/lib/session";
import {EvaluationForm,PollVoteForms} from "@/components/decision-actions";
import {ContextContribution} from "@/components/context-contribution";
import {PollCreateForm} from "@/components/poll-create-form";

const labels:Record<string,string>={WEEKLY_STUDY_HOURS:"Haftalık çalışma",ATTENDANCE_LEVEL:"Devam zorunluluğu",PROJECT_INTENSITY:"Proje yoğunluğu",EXAM_INTENSITY:"Sınav yoğunluğu",ENGLISH_PERCENT:"İngilizce kullanımı",GROUP_WORK_PERCENT:"Grup çalışması",CAMPUS_HOURS:"Kampüste geçirilen süre",MONTHLY_HOUSING_COST:"Aylık barınma",MONTHLY_TRANSPORT_COST:"Aylık ulaşım",MONTHLY_FOOD_COST:"Aylık yemek"};
const money=new Set(["MONTHLY_HOUSING_COST","MONTHLY_TRANSPORT_COST","MONTHLY_FOOD_COST"]);
function CategoryBars({items}:{items:Category[]}){const max=Math.max(...items.map(item=>item.count),1);return <ul className="data-bars">{items.map(item=><li key={item.label}><span>{item.label}</span><meter min="0" max={max} value={item.count}/><strong>{item.count}</strong></li>)}</ul>;}

export async function ContextInsights({universityId,programId,view="genel"}:{universityId:string;programId?:string;view?:"genel"|"degerlendirmeler"|"anketler"}) {
  let data;try{data=await getDecisionData(universityId,programId);}catch{return <section className="content-section"><h2>Karar verileri</h2><p className="muted">Karar verileri şu anda yüklenemiyor.</p></section>;}
  const user=await currentUser(),costs=data.metrics.filter(item=>money.has(item.metricKey)),life=data.metrics.filter(item=>!money.has(item.metricKey));
  if(view==="degerlendirmeler")return <section className="content-section university-tab-panel"><h2>Değerlendirmeler</h2><p className="muted">{data.summary.evaluationCount} topluluk değerlendirmesi · Ortalama {data.summary.averageRating.toLocaleString("tr-TR")} / 5</p><EvaluationForm universityId={universityId} programId={programId}/>{data.evaluations.length?<div className="insight-grid">{data.evaluations.map(item=><article key={item.id}><p className="rating" aria-label={`${item.rating} yıldız`}>{"★".repeat(item.rating)}{"☆".repeat(5-item.rating)}</p>{item.body&&<p>{item.body}</p>}<span>{item.authorName}</span></article>)}</div>:<div className="empty-state"><p>Henüz değerlendirme yok.</p></div>}</section>;
  if(view==="anketler")return <section className="content-section university-tab-panel"><h2>Anketler</h2><p className="muted">{data.polls.length} aktif anket</p>{user?.role==="TANIDIK"&&<PollCreateForm universityId={universityId} programId={programId}/>}<PollVoteForms polls={data.polls}/></section>;
  return <section id="genel" className="content-section"><h2>Karar verileri</h2>
    <div className="metric-grid"><div><strong>{data.summary.averageRating.toLocaleString("tr-TR")}</strong><span>5 üzerinden puan</span></div><div><strong>{data.summary.evaluationCount}</strong><span>değerlendirme</span></div><div><strong>{data.polls.length}</strong><span>anket</span></div></div>
    <ContextContribution universityId={universityId} programId={programId}/>
    {life.length>0&&<><h3>Gerçek hayat ölçümleri</h3><div className="metric-grid">{life.map(metric=><div key={metric.metricKey}><strong>{metric.privacyThresholdMet?metric.average?.toLocaleString("tr-TR"):"Gizli"}</strong><span>{labels[metric.metricKey]??metric.metricKey} · {metric.sampleSize} katkı ({metric.verifiedSampleSize} doğrulanmış)</span></div>)}</div></>}
    {costs.length>0&&<section aria-labelledby="cost-heading"><h3 id="cost-heading">Güncel öğrenci maliyeti</h3><p className="muted">Para değerleri yalnız bilgi amaçlıdır; iyi veya kötü olarak renklendirilmez.</p><div className="metric-grid neutral-metrics">{costs.map(metric=><div key={metric.metricKey}><strong>{metric.privacyThresholdMet?`${metric.average?.toLocaleString("tr-TR")} ₺`:"En az 5 katkı gerekli"}</strong><span>{labels[metric.metricKey]} · {metric.sampleSize} katkı · {new Date(metric.updatedAt).toLocaleDateString("tr-TR",{month:"long",year:"numeric"})}</span></div>)}</div></section>}
    {(data.sentiments.positives.length>0||data.sentiments.negatives.length>0)&&<div className="sentiment-grid"><section><h3>Öğrencilerin en sevdiği şeyler</h3><CategoryBars items={data.sentiments.positives}/></section><section><h3>En çok geliştirilmeli denilenler</h3><CategoryBars items={data.sentiments.negatives}/></section></div>}
    {data.career&&<section aria-labelledby="career-heading"><h3 id="career-heading">Bu program mezunları nereye gidiyor?</h3>{data.career.privacyThresholdMet?<><p>{data.career.sampleSize} anonim mezun katkısı · Ortalama ilk iş bulma süresi {data.career.averageJobSearchMonths?.toLocaleString("tr-TR")} ay · {data.career.graduateStudyCount} yüksek lisans</p><h4>Sektörler</h4><CategoryBars items={data.career.sectors}/><h4>İlk roller</h4><CategoryBars items={data.career.firstRoles}/><h4>Şirket türleri</h4><CategoryBars items={data.career.companyTypes}/></>:<p className="empty-state">Mezun gizliliği için sonuçlar en az 5 katkıdan sonra gösterilir. Şu an {data.career.sampleSize} katkı var.</p>}</section>}
    {data.experiences.length>0&&<><h3>Yapılandırılmış deneyimler</h3><div className="insight-grid">{data.experiences.map(item=><article key={item.id} data-sentiment={item.sentiment}><p className="eyebrow">{item.templateType}</p><h3>{item.title}</h3><p>{item.body}</p><span>{item.authorName}</span></article>)}</div></>}
  </section>;
}
