import Link from "next/link";
import {getTanidik,type PublicTanidik} from "@/lib/api/profiles";
import {LeaderboardHelp} from "@/components/leaderboard-help";
type Entry={userId:string;displayName:string;points:number;eventCount:number;title:string;badges:string[];lastEventAt:string};
export const metadata={title:"Katkı sıralaması",description:"TanıdıkVar topluluğuna en kaliteli katkıları sunan üyeler."};
const periods=[{value:"DAILY",label:"Bugün"},{value:"WEEKLY",label:"Bu hafta"},{value:"MONTHLY",label:"Bu ay"},{value:"YEARLY",label:"Bu yıl"},{value:"ALL_TIME",label:"Tüm zamanlar"}] as const;
async function entries(period:string){try{const response=await fetch(new URL(`/api/gamification/leaderboard?period=${period}&size=50`,process.env.API_BASE_URL??"http://localhost:8080"),{cache:"no-store"});return response.ok?await response.json() as Entry[]:[];}catch{return[];}}
const initials=(name:string)=>name.split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]).join("").toLocaleUpperCase("tr-TR");
export default async function Page({searchParams}:{searchParams:Promise<{period?:string}>}){const requested=(await searchParams).period,period=periods.some(item=>item.value===requested)?requested!:"ALL_TIME",items=await entries(period),profiles=new Map<string,PublicTanidik|null>(await Promise.all(items.map(async item=>[item.userId,await getTanidik(item.userId).catch(()=>null)] as const)));return <section className="content-section leaderboard-page"><p className="eyebrow">Kaliteli katkı</p><div className="leaderboard-title"><h1>Katkı sıralaması</h1><LeaderboardHelp/></div><nav className="leaderboard-periods">{periods.map(item=><Link className={period===item.value?"active":""} href={item.value==="ALL_TIME"?"/siralama":`/siralama?period=${item.value}`} key={item.value}>{item.label}</Link>)}</nav><div className="leaderboard-results">{items.length?<ol className="leaderboard legacy-role-leaderboard">{items.map((item,index)=>{const profile=profiles.get(item.userId);return <li key={item.userId}><strong>{index+1}</strong><Link className={`legacy-avatar role-${(profile?.educationStatus??"user").toLowerCase()}${profile?.activeTanidik?" is-tanidik":""}`} href={`/tanidik/${item.userId}`}><span>{initials(item.displayName)}</span>{profile?.activeTanidik&&<i>★★★</i>}</Link><div><Link href={`/tanidik/${item.userId}`}>{item.displayName}</Link><span>{item.title} · {item.eventCount} katkı</span></div><div><b>{item.points} puan</b>{item.badges.length>0&&<span>{item.badges.join(" · ")}</span>}</div></li>})}</ol>:<div className="empty-state"><h2>Bu dönemde henüz sıralama oluşmadı</h2><p>Doğrulanmış katkılar geldikçe burada görünür.</p></div>}</div></section>}
