import Link from "next/link";
import {getTanidiklar} from "@/lib/api/profiles";
import {getUniversities,getUniversityDepartments} from "@/lib/api/catalog";
import {Button,ButtonLink} from "@/components/ui";

type Params={q?:string;sayfa?:string;universityId?:string;departmentId?:string;educationStatus?:string;classYear?:string;verified?:string;expertise?:string};
type Props={searchParams:Promise<Params>};
const expertiseOptions=["Dersler","Kariyer","Erasmus","Hazırlık","Kampüs","Yurt","Sosyal Hayat"];

export default async function FamiliarPeoplePage({searchParams}:Props){
 const params=await searchParams,query=(params.q??"").trim().slice(0,200),page=Math.max(1,Number.parseInt(params.sayfa??"1",10)||1),classYear=params.classYear?Number(params.classYear):undefined,verified=params.verified==="true"?true:undefined;
 const [universities,programs]=await Promise.all([getUniversities({size:100}).catch(()=>null),params.universityId?getUniversityDepartments(params.universityId).catch(()=>[]):Promise.resolve([])]);
 let result;try{result=await getTanidiklar(query,page-1,{universityId:params.universityId,departmentId:params.departmentId,educationStatus:params.educationStatus,classYear,verified,expertise:params.expertise});}catch{return <section className="content-section"><h1>Doğru kişiye ulaş</h1><div className="empty-state"><h2>Tanıdıklar yüklenemiyor</h2><p>Daha sonra yeniden deneyebilirsin.</p></div></section>}
 const pageHref=(value:number)=>{const next=new URLSearchParams(Object.entries(params).filter(([,item])=>Boolean(item)) as [string,string][]);next.set("sayfa",String(value));return`/tanidiklar?${next}`;};
 return <section className="content-section"><h1>Doğru kişiye ulaş</h1><p className="lead">Üniversite, bölüm, sınıf, mezuniyet, eğitim doğrulaması ve uzmanlık alanına göre güvenilir deneyim sahiplerini bul.</p>
  <form className="legacy-question-search tanidik-search" action="/tanidiklar" role="search"><label className="sr-only" htmlFor="tanidik-query">Tanıdık ara</label><input id="tanidik-query" name="q" defaultValue={query} placeholder="İsim veya uzmanlık ara"/><details open={Object.entries(params).some(([key,value])=>key!=="q"&&Boolean(value))}><summary>Filtrele</summary><div className="ui-filter-panel legacy-filter-panel"><label>Üniversite<select name="universityId" defaultValue={params.universityId??""}><option value="">Tümü</option>{universities?.items.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Bölüm<select name="departmentId" defaultValue={params.departmentId??""} disabled={!params.universityId}><option value="">Tümü</option>{programs.map(item=><option value={item.departmentId} key={item.id}>{item.departmentName}</option>)}</select></label><label>Durum<select name="educationStatus" defaultValue={params.educationStatus??""}><option value="">Tümü</option><option value="UNIVERSITE_OGRENCISI">Öğrenci</option><option value="MEZUN">Mezun</option></select></label><label>Sınıf<select name="classYear" defaultValue={params.classYear??""}><option value="">Tümü</option>{[1,2,3,4,5,6].map(value=><option key={value}>{value}</option>)}</select></label><label>Uzmanlık<select name="expertise" defaultValue={params.expertise??""}><option value="">Tümü</option>{expertiseOptions.map(value=><option key={value}>{value}</option>)}</select></label><label className="checkbox-row"><input type="checkbox" name="verified" value="true" defaultChecked={verified}/> Eğitim kimliği doğrulanmış</label><Button>Filtrele</Button>{Object.values(params).some(Boolean)&&<ButtonLink tone="secondary" href="/tanidiklar">Tümünü temizle</ButtonLink>}</div></details><Button>Ara</Button></form>
  {result.items.length?<ul className="legacy-admin-grid">{result.items.map(person=><li key={person.id}><Link className="legacy-admin-card" href={`/tanidik/${person.id}`}><span className={`legacy-admin-avatar role-${(person.educationStatus??"user").toLowerCase()}`}><span>{person.name.split(/\s+/).slice(0,2).map(part=>part[0]).join("").toLocaleUpperCase("tr-TR")}</span><i>★★★</i></span><div><h2>{person.name}</h2><p>{[person.universityName,person.departmentName,person.classYear?`${person.classYear}. sınıf`:person.graduationYear?`${person.graduationYear} mezunu`:null].filter(Boolean).join(" · ")}</p><b>Tanıdık</b><span><strong>{person.tanidikAnswerCount}</strong> Tanıdık yorumu　·　<strong>{person.communityAnswerCount}</strong> topluluk yorumu</span>{person.educationVerified&&<small>✓ Eğitim kimliği doğrulandı</small>}</div></Link></li>)}</ul>:<div className="empty-state"><h2>Tanıdık bulunamadı</h2><p>Filtreyi değiştirerek yeniden deneyebilir veya kendi deneyiminle Tanıdık olabilirsin.</p><ButtonLink href="/hesabim/tanidik-basvurusu">Tanıdık ol</ButtonLink></div>}
  {result.totalElements>result.size&&<nav className="pagination" aria-label="Tanıdık sayfaları">{page>1&&<Link href={pageHref(page-1)}>Önceki</Link>}<span>Sayfa {page}</span>{page*result.size<result.totalElements&&<Link href={pageHref(page+1)}>Sonraki</Link>}</nav>}
 </section>;
}
