import { expect,test } from '@playwright/test'
import { randomUUID } from 'node:crypto'
import { account,completeProfile,promoteTestManager } from './accounts'

test('questions, comments, filters, stale forms, moderation and archives work together',async({page,request,browser},info)=>{
 test.setTimeout(180_000)
 const suffix=randomUUID().slice(0,8)
 await account(page,request);await page.goto('/questions/new')
 await expect(page.getByRole('heading',{name:'Önce profilini tamamla.'})).toBeVisible()
 await completeProfile(page)
 for(const scope of ['GENERAL','UNIVERSITY','UNIVERSITY_DEPARTMENT']){
  await page.goto('/questions/new');await page.getByLabel('Soru başlığı').fill(`${scope} Kampüs hayatı nasıl ${suffix}?`)
  await page.getByLabel('Açıklama (isteğe bağlı)').fill('Dersler ve sosyal hayat hakkında deneyimlerinizi merak ediyorum.')
  await page.getByLabel('Soru kapsamı').selectOption(scope)
  if(scope!=='GENERAL'){
   await page.getByLabel('Üniversite',{exact:true}).selectOption({label:'Dokuz Eylül Üniversitesi'})
   if(scope==='UNIVERSITY_DEPARTMENT')await page.getByLabel('Bölüm',{exact:true}).selectOption({label:'Bilgisayar Mühendisliği'})
  }
  await page.getByLabel('Tag seç',{exact:true}).selectOption({label:'Erasmus'})
  await page.getByRole('button',{name:'Soruyu yayınla'}).click()
  await expect(page.getByRole('heading',{level:1})).toHaveText(`${scope} Kampüs hayatı nasıl ${suffix}?`)
  await expect(page.getByText('1 görüntülenme',{exact:true})).toBeVisible()
 }
 const detail=page.url(),id=new URL(detail).pathname.split('/').pop()!
 const counters=page.getByRole('region',{name:'Soru etkileşimleri'})
 await page.getByRole('button',{name:'Beğen',exact:true}).click();await expect(counters.getByText('1 beğeni',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Beğeniyi geri al'}).click();await expect(counters.getByText('0 beğeni',{exact:true})).toBeVisible()
 await page.request.get('/api/questions/'+id)
 expect((await (await page.request.get('/api/questions/'+id+'/statistics')).json()).viewCount).toBe(1)
 await page.reload();await expect(counters.getByText('2 görüntülenme',{exact:true})).toBeVisible()
 await page.getByRole('tab',{name:/Topluluk yorumları/}).click();await page.getByRole('button',{name:'Topluluk yorumu yap'}).click()
 const reply=`Kampüs deneyimim ${suffix}: <script>alert(1)</script>`
 await page.getByRole('textbox',{name:'Yorumun',exact:true}).fill(reply)
 await page.getByRole('button',{name:'Yorumu yayınla'}).click()
 await expect(page.getByRole('tab',{name:'Topluluk yorumları (1)'})).toBeVisible()
 await page.locator('.own-answer').getByRole('button',{name:'Düzenle',exact:true}).click()
 const other=await page.context().newPage();await other.goto(detail+'?tab=community')
 await other.locator('.own-answer').getByRole('button',{name:'Düzenle',exact:true}).click()
 await page.getByRole('textbox',{name:'Yorumunu düzenle'}).fill(reply+' Güncel bilgi.')
 await page.getByRole('button',{name:'Yorum değişikliklerini kaydet'}).click();await expect(page.getByRole('dialog')).toHaveCount(0)
 await other.getByRole('textbox',{name:'Yorumunu düzenle'}).fill(reply+' Eski sekme.')
 await other.getByRole('button',{name:'Yorum değişikliklerini kaydet'}).click()
 await expect(other.getByRole('button',{name:'Güncel yorumumu yükle'})).toBeVisible();await other.close()
 await page.locator('.own-answer').getByRole('button',{name:'Sil',exact:true}).click()
 await expect(page.getByRole('tab',{name:'Topluluk yorumları (0)'})).toBeVisible()
 await page.getByRole('button',{name:'Geri yükle',exact:true}).click()
 await expect(page.getByRole('tab',{name:'Topluluk yorumları (1)'})).toBeVisible()
 await page.goto('/my-answers');await expect(page.getByText(reply+' Güncel bilgi.',{exact:true})).toBeVisible()
 await page.getByRole('link',{name:'Soru detayı',exact:true}).click();await expect(page.getByRole('tab',{name:/Topluluk yorumları/})).toHaveAttribute('aria-selected','true')
 await page.getByRole('link',{name:'Soruyu düzenle'}).click()
 await expect(page.getByLabel('Açıklama (isteğe bağlı)')).toHaveValue('Dersler ve sosyal hayat hakkında deneyimlerinizi merak ediyorum.')
 const stale=await page.context().newPage();await stale.goto(page.url());await expect(stale.getByLabel('Soru başlığı')).toBeVisible()
 await page.getByLabel('Açıklama (isteğe bağlı)').fill('Güncel soru açıklaması.')
 await page.getByRole('button',{name:'Değişiklikleri kaydet'}).click();await expect(page.getByText('Güncel soru açıklaması.',{exact:true})).toBeVisible()
 await stale.getByLabel('Soru başlığı').fill('Eski sekmedeki soru '+suffix);await stale.getByRole('button',{name:'Değişiklikleri kaydet'}).click();await expect(stale.getByRole('button',{name:'Güncel soruyu yükle'})).toBeVisible();await stale.close()
 await page.goto('/questions?q='+suffix);await expect(page.locator('.question-card')).toHaveCount(3)
 await page.getByRole('button',{name:/^Filtrele/}).click();await page.getByRole('button',{name:'Tümünü temizle'}).click();await expect(page.getByLabel('Soru ara')).toHaveValue('')
 for(const period of ['DAILY','WEEKLY','MONTHLY','YEARLY']){await page.goto(`/popular?q=${suffix}&period=${period}`);await expect(page.locator('.question-card')).toHaveCount(3)}
 const managerContext=await browser.newContext({baseURL:info.project.use.baseURL,viewport:info.project.use.viewport}),manager=await managerContext.newPage()
 const email=await account(manager,request);promoteTestManager(email)
 const before=(await (await page.request.get('/api/questions/'+id+'/statistics')).json()).viewCount
 await manager.goto('/manager/questions/'+id);await expect(manager.getByRole('heading',{name:'Soru ve yorum incelemesi'})).toBeVisible()
 await manager.getByRole('button',{name:'Düzenle',exact:true}).click();await expect(manager.getByRole('dialog')).toBeVisible()
 await manager.getByLabel('Soru başlığı').fill('Manager tarafından güncellenen soru '+suffix);await manager.getByLabel('Soru açıklaması').fill('Manager tarafından güncellenen açıklama.');await manager.getByLabel('Soru kapsamı').selectOption('GENERAL');await manager.getByLabel('Düzeltme gerekçesi').fill('Kapsam incelemesi')
 await manager.getByRole('button',{name:'Soruyu kaydet'}).click();await expect(manager.getByRole('dialog')).toHaveCount(0)
 expect((await (await page.request.get('/api/questions/'+id+'/statistics')).json()).viewCount).toBe(before)
 await expect(manager.getByText('Manager tarafından güncellenen açıklama.',{exact:true})).toBeVisible()
 const updated=await (await page.request.get('/api/questions/'+id)).json();expect(updated.title).toBe('Manager tarafından güncellenen soru '+suffix);expect(updated.body).toBe('Manager tarafından güncellenen açıklama.')
 const comment=manager.locator('.is-comment')
 await comment.getByRole('button',{name:'İçeriği gizle',exact:true}).click();await comment.getByLabel('İşlem gerekçesi').fill('Yorum incelemesi')
 await comment.getByRole('button',{name:'İçeriği gizle — onayla'}).click();await expect(comment.getByRole('button',{name:'İçeriği geri yükle',exact:true})).toBeVisible()
 await page.goto(detail+'?tab=community');await expect(page.getByText('Yorumun Manager tarafından gizlendi.')).toBeVisible();await expect(page.locator('.own-answer').getByRole('button',{name:'Düzenle',exact:true})).toHaveCount(0)
 await comment.getByRole('button',{name:'İçeriği geri yükle',exact:true}).click();await comment.getByLabel('İşlem gerekçesi').fill('İnceleme tamamlandı')
 await comment.getByRole('button',{name:'İçeriği geri yükle — onayla'}).click();await expect(comment.getByRole('button',{name:'İçeriği gizle',exact:true})).toBeVisible()
 await page.reload();await page.getByRole('button',{name:'Arşivle',exact:true}).click();await page.getByRole('button',{name:'Arşivlemeyi onayla'}).click();await expect(page.getByText(/Bu soru arşivlendi/)).toBeVisible()
 await page.getByRole('tab',{name:/Topluluk yorumları/}).click();await expect(page.locator('.own-answer').getByRole('button',{name:'Sil',exact:true})).toBeVisible()
 await page.goto('/questions?q='+suffix);await expect(page.locator('.question-card')).toHaveCount(2)
 await page.goto('/my-questions');await expect(page.locator(`a[href="/questions/${id}"]`)).toBeVisible()
 const anonymous=await browser.newContext({baseURL:info.project.use.baseURL,viewport:info.project.use.viewport}),reader=await anonymous.newPage()
 await reader.goto(detail);await expect(reader.getByText(/Bu soru arşivlendi/)).toBeVisible();await expect(reader.getByRole('link',{name:'Soruyu düzenle'})).toHaveCount(0)
 expect(await reader.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await manager.screenshot({path:info.outputPath('moderation.png'),fullPage:true});await reader.screenshot({path:info.outputPath('archive.png'),fullPage:true})
 await anonymous.close();await managerContext.close()
})
