import { expect,test,type APIRequestContext } from '@playwright/test'
import { randomUUID } from 'node:crypto'
import { account,promoteTestManager } from './accounts'
async function create(request:APIRequestContext,path:string,data:unknown){
  const csrf=await request.get('/api/auth/csrf');const {token}=await csrf.json()
  const response=await request.post(path,{data,headers:{'X-XSRF-TOKEN':token}})
  expect(response.status()).toBe(201);return response.json()
}
test('questions support all scopes, filtering, editing, stale forms and readable archives',async({page,request,browser},info)=>{
  await account(page,request)
  await page.goto('/questions/new');await expect(page.getByRole('heading',{name:'Önce profilini tamamla.'})).toBeVisible()
  await page.getByRole('link',{name:'Profilini tamamla'}).click()
  await page.getByLabel('Ad',{exact:true}).fill('Deniz');await page.getByLabel('Soyad',{exact:true}).fill('Yılmaz')
  await page.getByRole('button',{name:'Profili kaydet'}).click();await expect(page.getByText('Profilin kaydedildi.')).toBeVisible()
  const managerContext=await browser.newContext({baseURL:info.project.use.baseURL,viewport:info.project.use.viewport})
  const manager=await managerContext.newPage();const managerEmail=await account(manager,request);promoteTestManager(managerEmail);await manager.goto('/manager')
  await expect(manager.getByRole('heading',{name:'Platforma genel bakış'})).toBeVisible()
  const suffix=randomUUID().slice(0,8)
  const university=await create(manager.request,'/api/manager/catalog/UNIVERSITY',{name:`Test Üniversitesi ${suffix}`,reason:'Tarayıcı test kataloğu'})
  const department=await create(manager.request,'/api/manager/catalog/DEPARTMENT',{name:`Test Bölümü ${suffix}`,reason:'Tarayıcı test kataloğu'})
  await create(manager.request,'/api/manager/university-departments',{universityId:university.id,departmentId:department.id,reason:'Tarayıcı test eşleşmesi'})
  const tag=await create(manager.request,'/api/manager/catalog/TAG',{name:`Test Kampüs ${suffix}`,reason:'Tarayıcı test kataloğu'})
  for(const scope of ['GENERAL','UNIVERSITY','UNIVERSITY_DEPARTMENT']){
    await page.goto('/questions/new');await page.getByLabel('Soru başlığı').fill(`${scope} Kampüs hayatı nasıl ${suffix}?`)
    await page.getByLabel('Açıklama (isteğe bağlı)').fill('Dersler ve sosyal hayat hakkında deneyimlerinizi merak ediyorum.')
    await page.getByLabel('Soru kapsamı').selectOption(scope)
    if(scope!=='GENERAL'){
      await page.getByLabel('Üniversite',{exact:true}).selectOption({label:university.name})
      if(scope==='UNIVERSITY_DEPARTMENT')await page.getByLabel('Bölüm',{exact:true}).selectOption({label:department.name})
    }
    await page.getByLabel('Tag seç',{exact:true}).selectOption({label:tag.name})
    await page.getByRole('button',{name:'Soruyu yayınla'}).click();await expect(page.getByRole('heading',{level:1})).toHaveText(`${scope} Kampüs hayatı nasıl ${suffix}?`);await expect(page.getByRole('region',{name:'Soru etkileşimleri'}).getByText('1 görüntülenme',{exact:true})).toBeVisible()
  }
  await expect(page.locator('.scope-university_department')).toBeVisible()
  const detailUrl=page.url()
  const questionId=new URL(detailUrl).pathname.split('/').pop()
  const counters=page.getByRole('region',{name:'Soru etkileşimleri'})
  await expect(counters.getByText('1 görüntülenme',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Beğen',exact:true}).click();await expect(counters.getByText('1 beğeni',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Beğeniyi geri al'}).click();await expect(counters.getByText('0 beğeni',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Beğen',exact:true}).click();await expect(counters.getByText('1 beğeni',{exact:true})).toBeVisible()
  await page.request.get(`/api/questions/${questionId}`)
  expect((await (await page.request.get(`/api/questions/${questionId}/statistics`)).json()).viewCount).toBe(1)
  await page.reload();await expect(counters.getByText('2 görüntülenme',{exact:true})).toBeVisible()
  await page.screenshot({path:info.outputPath('question-engagement.png'),fullPage:true})
  const reply=`Kampüste kulüpler ve dersler birlikte güzel ilerliyor ${suffix}.`
  await page.getByLabel('Cevabın',{exact:true}).fill(reply)
  await page.getByRole('button',{name:'Cevabı yayınla'}).click()
  await expect(page.getByText('1 topluluk cevabı',{exact:true})).toBeVisible();await expect(counters.getByText('1 cevap',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Cevabımı düzenle'}).click()
  const staleAnswer=await page.context().newPage();await staleAnswer.goto(detailUrl)
  await staleAnswer.getByRole('button',{name:'Cevabımı düzenle'}).click()
  await page.getByLabel('Cevabını düzenle',{exact:true}).fill(`${reply} Ek deneyim: <script>alert(1)</script>`)
  await page.getByRole('button',{name:'Cevap değişikliklerini kaydet'}).click()
  await expect(page.getByText(/Cevap düzenlendi ·/)).toBeVisible()
  await staleAnswer.getByLabel('Cevabını düzenle',{exact:true}).fill(`${reply} Eski sekmedeki değişiklik.`)
  await staleAnswer.getByRole('button',{name:'Cevap değişikliklerini kaydet'}).click()
  await expect(staleAnswer.getByRole('button',{name:'Güncel cevabımı yükle'})).toBeVisible();await staleAnswer.close()
  await page.getByRole('button',{name:'Cevabımı kaldır'}).click();await page.getByRole('button',{name:'Kaldırmayı onayla'}).click()
  await expect(page.getByText('0 topluluk cevabı',{exact:true})).toBeVisible();await expect(counters.getByText('0 cevap',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Cevabı geri yükle'}).click()
  await expect(page.getByText('1 topluluk cevabı',{exact:true})).toBeVisible();await expect(counters.getByText('1 cevap',{exact:true})).toBeVisible()
  await expect(page.getByLabel('Cevabın',{exact:true})).toHaveCount(0)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:info.outputPath('community-answers.png'),fullPage:true})
  await page.goto('/account')
  await expect(page.getByRole('navigation',{name:'Ana menü'}).getByRole('link',{name:'Sorularım'})).toHaveCount(0)
  await page.getByRole('link',{name:'Yorumlarım',exact:true}).click()
  await expect(page.getByText(`${reply} Ek deneyim: <script>alert(1)</script>`,{exact:true})).toBeVisible()
  await expect(page.getByRole('link',{name:'Soruyu aç'})).toHaveAttribute('href',`/questions/${questionId}`)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:info.outputPath('my-comments.png'),fullPage:true})
  await manager.goto(`/manager/content?kind=COMMUNITY&q=${suffix}`)
  await manager.getByRole('button',{name:'İçeriği gizle',exact:true}).click()
  await manager.getByLabel('İşlem gerekçesi').fill('Topluluk cevabı moderasyon testi.')
  await manager.getByRole('button',{name:'İçeriği gizle — onayla'}).click()
  await expect(manager.getByRole('button',{name:'İçeriği geri yükle',exact:true})).toBeVisible()
  expect(await manager.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await manager.screenshot({path:info.outputPath('manager-content.png'),fullPage:true})
  await page.goto(detailUrl);await expect(page.getByText(/Cevabın Manager tarafından gizlendi/)).toBeVisible()
  await expect(page.getByText('0 topluluk cevabı',{exact:true})).toBeVisible()
  await expect(page.getByRole('button',{name:'Cevabımı düzenle'})).toHaveCount(0)
  await page.goto('/account')
  await expect(page.getByRole('navigation',{name:'Ana menü'}).getByRole('link',{name:'Sorularım'})).toHaveCount(0)
  await page.getByRole('link',{name:'Yorumlarım',exact:true}).click()
  await expect(page.getByText(`${reply} Ek deneyim: <script>alert(1)</script>`,{exact:true})).toBeVisible()
  await expect(page.getByRole('link',{name:'Soruyu aç'})).toHaveAttribute('href',`/questions/${questionId}`)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:info.outputPath('my-comments.png'),fullPage:true})
  await manager.goto(`/manager/content?kind=COMMUNITY&q=${suffix}`)
  await manager.getByRole('button',{name:'İçeriği geri yükle',exact:true}).click()
  await manager.getByLabel('İşlem gerekçesi').fill('İnceleme tamamlandı.')
  await manager.getByRole('button',{name:'İçeriği geri yükle — onayla'}).click()
  await expect(manager.getByRole('button',{name:'İçeriği gizle',exact:true})).toBeVisible()
  await page.goto('/questions')
  await page.getByLabel('Soru ara').fill('kampus hayati nasil '+suffix)
  await page.getByRole('button',{name:'Ara',exact:true}).click();await expect(page.locator('.question-card')).toHaveCount(3)
  await page.screenshot({path:info.outputPath('search-results.png'),fullPage:true})
  await page.goto(`/popular?q=${suffix}&period=DAILY`)
  await expect(page.locator('.question-card')).toHaveCount(3)
  await expect(page.locator('.question-card').first().getByRole('link')).toHaveAttribute('href','/questions/'+questionId)
  for(const period of ['WEEKLY','MONTHLY','YEARLY']){await page.getByLabel('Zaman aralığı').selectOption(period);await expect(page).toHaveURL(new RegExp('period='+period));await expect(page.locator('.question-card')).toHaveCount(3)}
  await page.reload();await expect(page.getByLabel('Zaman aralığı')).toHaveValue('YEARLY');await expect(page.locator('.question-card')).toHaveCount(3)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:info.outputPath('popular.png'),fullPage:true})
  await page.goto(`/questions?universityId=${university.id}&tagId=${tag.id}`)
  await expect(page.locator('.question-card')).toHaveCount(2)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:info.outputPath('questions.png'),fullPage:true})
  await page.goto(detailUrl);await page.getByRole('link',{name:'Soruyu düzenle'}).click()
  const stale=await page.context().newPage();await stale.goto(page.url());await expect(stale.getByLabel('Soru başlığı')).toBeVisible()
  await page.getByLabel('Açıklama (isteğe bağlı)').fill('Güncel soru açıklaması <script>alert(1)</script>')
  await page.getByRole('button',{name:'Değişiklikleri kaydet'}).click();await expect(page.getByText(/Düzenlendi ·/)).toBeVisible()
  await stale.getByLabel('Soru başlığı').fill(`Eski formdaki soru başlığı ${suffix}`);await stale.getByRole('button',{name:'Değişiklikleri kaydet'}).click()
  await expect(stale.getByRole('button',{name:'Güncel soruyu yükle'})).toBeVisible();await stale.close()
  await page.getByRole('button',{name:'Arşivle',exact:true}).click();await page.getByRole('button',{name:'Arşivlemeyi onayla'}).click()
  await expect(page.getByText(/Bu soru arşivlendi/)).toBeVisible()
  await expect(page.getByRole('button',{name:'Cevabımı düzenle'})).toHaveCount(0)
  await expect(page.getByRole('button',{name:'Cevabımı kaldır'})).toBeVisible()
  await page.screenshot({path:info.outputPath('question-detail.png'),fullPage:true})
  await page.goto(`/questions?universityId=${university.id}&tagId=${tag.id}`);await expect(page.locator('.question-card')).toHaveCount(1)
  await page.goto(`/popular?q=${suffix}`);await expect(page.locator('.question-card')).toHaveCount(2);await expect(page.locator(`.question-card a[href="/questions/${questionId}"]`)).toHaveCount(0)
  await page.goto('/my-questions');await expect(page.getByRole('link',{name:`UNIVERSITY_DEPARTMENT Kampüs hayatı nasıl ${suffix}?`})).toBeVisible()
  const anonymous=await browser.newContext();const reader=await anonymous.newPage()
  try{const before=(await (await page.request.get(`/api/questions/${questionId}/statistics`)).json()).viewCount;await reader.goto(detailUrl);await expect(reader.getByText(`${before+1} görüntülenme`,{exact:true})).toBeVisible();await reader.reload();await expect(reader.getByText(`${before+2} görüntülenme`,{exact:true})).toBeVisible();await expect(reader.getByText(/Bu soru arşivlendi/)).toBeVisible();await expect(reader.getByRole('link',{name:'Soruyu düzenle'})).toHaveCount(0);await expect(reader.getByText('1 topluluk cevabı',{exact:true})).toBeVisible();await expect(reader.getByRole('button',{name:'Cevabımı kaldır'})).toHaveCount(0)}finally{await anonymous.close()}
  const beforeManager=(await (await manager.request.get(`/api/questions/${questionId}/statistics`)).json()).viewCount
  await manager.goto(`/manager/questions/${questionId}`);await expect(manager.getByRole('heading',{name:'Soru ve cevap incelemesi'})).toBeVisible()
  await manager.getByLabel('Soru kapsamı').selectOption('GENERAL');await manager.getByLabel('Düzeltme gerekçesi').fill('Arşiv soru kapsamı düzeltmesi')
  await manager.getByRole('button',{name:'Sınıflandırmayı kaydet'}).click();await expect(manager.getByLabel('Düzeltme gerekçesi')).toHaveValue('')
  expect((await (await manager.request.get(`/api/questions/${questionId}/statistics`)).json()).viewCount).toBe(beforeManager)
  await manager.screenshot({path:info.outputPath('manager-question-review.png'),fullPage:true})
  await managerContext.close()

})
