"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {apiRequest} from "@/lib/client-api";
import {catalogSegment,questionSegment} from "@/lib/public-url";
import {QuestionCard} from "@/components/question-card";
import type {QuestionItem} from "@/lib/api/questions";
import {ModalShell} from "@/components/modal-shell";
import {NotificationPreferences} from "@/components/notification-preferences";
import {Button} from "@/components/ui";
import {plainProgramName} from "@/lib/program-label";

type Item={id:string;targetType:string;targetId:string;createdAt?:string};
type Note=Item&{title:string;body:string;readAt:string|null};type Page<T>={items:T[];totalElements:number};
type Resolved=Item&{label:string;detail:string;href:string;kind?:string;role?:string;question?:QuestionItem};
type University={id:string;name:string};type Person={id:string;name:string;universityName?:string|null;departmentName?:string|null;educationStatus?:string|null};
async function resolveItem(item:Item):Promise<Resolved>{try{if(item.targetType==="QUESTION"){const value=await apiRequest<QuestionItem>(`/questions/${item.targetId}`);return{...item,label:value.title,detail:"Soru",question:value,href:`/soru/${questionSegment(value.title,value.id)}`};}if(item.targetType==="UNIVERSITY"){const value=await apiRequest<University>(`/universities/${item.targetId}`);return{...item,label:value.name,detail:"Üniversite",href:`/universite/${catalogSegment(value.name,value.id)}`};}if(item.targetType==="TANIDIK"){const value=await apiRequest<Person>(`/tanidiklar/${item.targetId}`);return{...item,label:value.name,detail:[value.universityName,plainProgramName(value.departmentName)].filter(Boolean).join(" · ")||"Deneyim sahibi Tanıdık",kind:"person",role:value.educationStatus??"USER",href:`/tanidik/${value.id}`};}if(item.targetType==="PROGRAM"){const value=await apiRequest<{summary:{id:string;name:string;universityName:string}}>(`/catalog-programs/${item.targetId}`).then(result=>result.summary).catch(()=>null);if(value)return{...item,label:plainProgramName(value.name),detail:value.universityName,href:`/program/${value.id}`};}}catch{}return{...item,label:"İçerik",detail:"İçerik artık yayında olmayabilir",href:"/sorular"};}

export function AccountDashboard({mode="all"}:{mode?:"all"|"saved"|"follows"|"notifications"}){
 const[saved,setSaved]=useState<Resolved[]|null>(null),[follows,setFollows]=useState<Resolved[]|null>(null),[notes,setNotes]=useState<Page<Note>|null>(null),[followType,setFollowType]=useState("UNIVERSITY");
 const[noteType,setNoteType]=useState(""),[unreadOnly,setUnreadOnly]=useState(false),[filter,setFilter]=useState({type:"",unread:false}),[settingsOpen,setSettingsOpen]=useState(false);
 useEffect(()=>{let active=true;void Promise.all([apiRequest<Page<Item>>("/me/saved?size=100"),apiRequest<Page<Item>>("/me/follows?size=100"),apiRequest<Page<Note>>("/me/notifications?size=100")]).then(async([s,f,n])=>{const[rs,rf]=await Promise.all([Promise.all(s.items.filter(item=>item.targetType==="QUESTION").map(resolveItem)),Promise.all(f.items.map(resolveItem))]);if(active){setSaved(rs);setFollows(rf);setNotes(n);}}).catch(()=>{if(active){setSaved([]);setFollows([]);setNotes({items:[],totalElements:0});}});return()=>{active=false};},[]);
 const list=(items:Resolved[]|null,empty:string)=>items===null?<p>Yükleniyor…</p>:items.length?<ul className="account-content-list">{items.map(item=><li className={item.kind==="person"?"account-person-item":""} key={item.id}><Link href={item.href}>{item.kind==="person"&&<span className={`account-person-avatar role-${(item.role??"user").toLowerCase()}`} aria-hidden="true">{item.label.split(/\s+/).slice(0,2).map(part=>part[0]).join("")}</span>}<span><strong>{item.label}</strong><small>{item.detail}</small></span><b aria-hidden="true">→</b></Link></li>)}</ul>:<p>{empty}</p>;
 const savedList=saved===null?<p>Yükleniyor…</p>:saved.length?<ul className="legacy-question-list saved-question-list">{saved.map(item=>item.question?<QuestionCard key={item.id} question={item.question}/>:<li key={item.id} className="saved-question-unavailable">İçerik artık yayında olmayabilir.</li>)}</ul>:<p>Henüz kaydettiğin bir soru yok.</p>;
 const heading=(label:string)=>mode==="all"?<h2>{label}</h2>:null,visibleFollows=follows?.filter(item=>item.targetType===followType)??follows,visibleNotes=notes?.items.filter(note=>(!filter.type||note.targetType===filter.type)&&(!filter.unread||!note.readAt))??[];
 return <div className="dashboard-grid">
  {(mode==="all"||mode==="follows")&&<section>{heading("Takipler")}<div className="segmented-tabs" role="tablist" aria-label="Takip türü">{[["UNIVERSITY","Üniversite"],["PROGRAM","Bölüm"],["QUESTION","Yorum"]].map(([value,label])=><button type="button" role="tab" aria-selected={followType===value} onClick={()=>setFollowType(value)} key={value}>{label}</button>)}</div>{list(visibleFollows,"Bu türde henüz takip ettiğin içerik yok.")}</section>}
  {(mode==="all"||mode==="saved")&&<section>{heading("Kaydedilen sorular")}{savedList}</section>}
  {(mode==="all"||mode==="notifications")&&<section className="notifications-panel">{heading("Bildirimler")}<div className="notifications-toolbar"><form className="notification-filters" onSubmit={event=>{event.preventDefault();setFilter({type:noteType,unread:unreadOnly});}}><label><span>Bildirim türü</span><select value={noteType} onChange={event=>setNoteType(event.target.value)}><option value="">Tümü</option><option value="QUESTION">Sorular</option><option value="ANSWER">Yorumlar</option><option value="APPLICATION">Başvurular</option><option value="ACCOUNT">Hesap</option></select></label><label className="check-label"><input type="checkbox" checked={unreadOnly} onChange={event=>setUnreadOnly(event.target.checked)}/><span>Yalnız okunmamışlar</span></label><div className="filter-actions"><Button>Filtrele</Button><Button tone="secondary" type="button" onClick={()=>{setNoteType("");setUnreadOnly(false);setFilter({type:"",unread:false});}}>Temizle</Button></div></form><Button className="notification-settings-button" tone="secondary" type="button" onClick={()=>setSettingsOpen(true)}>Bildirim ayarları</Button></div>{visibleNotes.length?<ul className="notification-list">{visibleNotes.map(note=><li key={note.id} className={note.readAt?"":"unread"}><Link href={note.targetType==="QUESTION"?`/soru/${note.targetId}`:note.targetType==="ANSWER"?"/hesabim/yorumlarim":"/hesabim"}><span className="notification-indicator" aria-hidden="true"/><span className="notification-copy"><strong>{note.title}</strong><span>{note.body}</span>{note.createdAt&&<time>{new Intl.DateTimeFormat("tr-TR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(note.createdAt))}</time>}</span><b aria-hidden="true">→</b></Link></li>)}</ul>:<div className="notification-empty"><strong>Bildirim bulunamadı</strong><span>Seçtiğin filtrelere uygun bir bildirim yok.</span></div>}</section>}
  <ModalShell open={settingsOpen} onClose={()=>setSettingsOpen(false)} title="Bildirim ayarları" className="notification-settings-dialog"><NotificationPreferences onSaved={()=>setSettingsOpen(false)}/></ModalShell>
 </div>;
}
