"use client";
import {useEffect,useMemo,useState,type FormEvent} from "react";import {useRouter} from "next/navigation";import {apiRequest,apiRequestAllPages} from "@/lib/client-api";import type {QuestionItem,QuestionScope} from "@/lib/api/questions";import {questionSegment} from "@/lib/public-url";
type University={id:string;name:string};type Education={id:string;departmentId:string;departmentName:string};type Template={id:string;category:string;title:string;body:string|null;scopeHint:string};
export function AskQuestionForm({initial}:{initial?:QuestionItem}){
 const router=useRouter(),[scope,setScope]=useState<QuestionScope>(initial?.scope??"GENERAL"),[universities,setUniversities]=useState<University[]>([]),[educations,setEducations]=useState<Education[]>([]),[universityId,setUniversityId]=useState(initial?.universityId??""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[templates,setTemplates]=useState<Template[]>([]),[category,setCategory]=useState(""),[selected,setSelected]=useState("");
 useEffect(()=>{apiRequestAllPages<University>("/universities").then(setUniversities).catch(()=>setError("Üniversiteler yüklenemedi."));if(!initial)apiRequest<Template[]>("/question-templates").then(setTemplates).catch(()=>undefined);},[initial]);
 useEffect(()=>{setEducations([]);if(!universityId||scope!=="UNIVERSITY_DEPARTMENT")return;apiRequestAllPages<Education>(`/universities/${universityId}/departments`).then(setEducations).catch(()=>setError("Programlar yüklenemedi."));},[scope,universityId]);
 const categories=useMemo(()=>[...new Set(templates.map(item=>item.category))],[templates]),visible=useMemo(()=>templates.filter(item=>!category||item.category===category),[templates,category]);
 function apply(id:string,form:HTMLFormElement|null){setSelected(id);const template=templates.find(item=>item.id===id);if(!template||!form)return;(form.elements.namedItem("title") as HTMLInputElement).value=template.title;(form.elements.namedItem("body") as HTMLTextAreaElement).value=template.body??"";if(["GENERAL","UNIVERSITY","UNIVERSITY_DEPARTMENT"].includes(template.scopeHint))setScope(template.scopeHint as QuestionScope);}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget),content={title:form.get("title"),body:form.get("body")||null,scope,universityId:scope==="GENERAL"?null:universityId,departmentId:scope==="UNIVERSITY_DEPARTMENT"?form.get("departmentId"):null,tagIds:initial?.tags.filter(tag=>tag.available).map(tag=>tag.id)??[]};try{const question=await apiRequest<QuestionItem>(initial?`/questions/${initial.id}`:"/questions",{method:initial?"PUT":"POST",body:JSON.stringify(initial?{version:initial.version,content}:{requestId:crypto.randomUUID(),content})});router.push(`/soru/${questionSegment(question.title,question.id)}`);}catch(reason){setError(reason instanceof Error?reason.message:"Soru kaydedilemedi.");}finally{setBusy(false);}}
 return <form className="stack-form wide" onSubmit={submit}>
  {!initial&&<details className="template-picker compact-template-picker"><summary><span>Ne soracağımı bilmiyorum</span><i aria-hidden="true">?</i><small>Hazır sorular</small></summary><div className="template-picker-content"><label><span className="sr-only">Hazır sorular</span><select value={selected} onChange={event=>apply(event.target.value,event.currentTarget.form)}><option value="">{visible.length} soru arasından seç</option>{visible.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><div className="filter-chips"><button type="button" className={!category?"active":""} onClick={()=>setCategory("")}>Tümü</button>{categories.map(item=><button type="button" className={category===item?"active":""} onClick={()=>setCategory(item)} key={item}>{item}</button>)}</div></div></details>}
  <label>Bağlam<select value={scope} onChange={event=>{setScope(event.target.value as QuestionScope);setUniversityId("");}}><option value="GENERAL">Genel</option><option value="UNIVERSITY">Üniversite</option><option value="UNIVERSITY_DEPARTMENT">Üniversite + bölüm</option></select></label>{scope!=="GENERAL"&&<label>Üniversite<select required value={universityId} onChange={event=>setUniversityId(event.target.value)}><option value="">Seç</option>{universities.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}{scope==="UNIVERSITY_DEPARTMENT"&&<label>Program<select name="departmentId" required defaultValue={initial?.departmentId??""}><option value="">Seç</option>{educations.map(item=><option key={item.id} value={item.departmentId}>{item.departmentName}</option>)}</select></label>}<label>Soru başlığı<input name="title" required minLength={10} maxLength={200} defaultValue={initial?.title}/></label><label>Ayrıntı <span className="optional-label">(isteğe bağlı)</span><textarea name="body" maxLength={5000} rows={8} defaultValue={initial?.body??""}/></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button" disabled={busy}>{busy?"Kaydediliyor…":initial?"Değişiklikleri kaydet":"Soruyu yayınla"}</button>
 </form>;
}
