"use client";
import {useEffect,useMemo,useState,type FormEvent} from "react";import {useRouter} from "next/navigation";import {apiRequest,apiRequestAllPages} from "@/lib/client-api";import type {QuestionItem,QuestionScope} from "@/lib/api/questions";import {questionSegment} from "@/lib/public-url";import {uniquePrograms} from "@/lib/program-label";
type University={id:string;name:string};type Education={id:string;name:string;faculties:string[];scoreTypes:string[];degreeLevel:string};type Template={id:string;category:string;title:string;body:string|null;scopeHint:string};type Tag={id:string;name:string;deletedAt:null;version:number};const turkish=new Intl.Collator("tr",{sensitivity:"base"});
export function AskQuestionForm({initial,onCancel}:{initial?:QuestionItem;onCancel?:()=>void}){
 const router=useRouter(),[scope,setScope]=useState<QuestionScope>(initial?.scope??"GENERAL"),[universities,setUniversities]=useState<University[]>([]),[educations,setEducations]=useState<(Education&{displayName:string})[]>([]),[tags,setTags]=useState<Tag[]>([]),[selectedTags,setSelectedTags]=useState<string[]>(initial?.tags.filter(tag=>tag.available).map(tag=>tag.id)??[]),[universityId,setUniversityId]=useState(initial?.universityId??""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[templates,setTemplates]=useState<Template[]>([]),[category,setCategory]=useState(""),[selected,setSelected]=useState("");
 useEffect(()=>{void Promise.all([apiRequestAllPages<University>("/universities"),apiRequestAllPages<Tag>("/tags")]).then(([items,tagItems])=>{setUniversities(items.toSorted((a,b)=>turkish.compare(a.name,b.name)));setTags(tagItems.toSorted((a,b)=>turkish.compare(a.name,b.name)));}).catch(()=>setError("Form seçenekleri yüklenemedi."));if(!initial)apiRequest<Template[]>("/question-templates").then(setTemplates).catch(()=>undefined);},[initial]);
 useEffect(()=>{setEducations([]);if(!universityId||scope!=="UNIVERSITY_DEPARTMENT")return;apiRequestAllPages<Education>(`/catalog-programs?universityId=${universityId}`).then(items=>setEducations(uniquePrograms(items))).catch(()=>setError("Programlar yüklenemedi."));},[scope,universityId]);
 const categories=useMemo(()=>[...new Set(templates.map(item=>item.category))],[templates]),visible=useMemo(()=>templates.filter(item=>!category||item.category===category),[templates,category]);
 function apply(id:string,form:HTMLFormElement|null){setSelected(id);const template=templates.find(item=>item.id===id);if(!template||!form)return;(form.elements.namedItem("title") as HTMLInputElement).value=template.title;(form.elements.namedItem("body") as HTMLTextAreaElement).value=template.body??"";if(["GENERAL","UNIVERSITY","UNIVERSITY_DEPARTMENT"].includes(template.scopeHint))setScope(template.scopeHint as QuestionScope);}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget),content={title:form.get("title"),body:form.get("body")||null,scope,universityId:scope==="GENERAL"?null:universityId,programId:scope==="UNIVERSITY_DEPARTMENT"?form.get("programId"):null,departmentId:null,tagIds:selectedTags};try{const question=await apiRequest<QuestionItem>(initial?`/questions/${initial.id}`:"/questions",{method:initial?"PUT":"POST",body:JSON.stringify(initial?{version:initial.version,content}:{requestId:crypto.randomUUID(),content})});router.push(`/soru/${questionSegment(question.title,question.id)}`);}catch(reason){setError(reason instanceof Error?reason.message:"Soru kaydedilemedi.");}finally{setBusy(false);}}
 return <form className="stack-form wide" onSubmit={submit}>
  {!initial&&<details className="template-picker compact-template-picker"><summary><span className="template-help-icon" aria-hidden="true">?</span><span><strong>Ne soracağımı bilmiyorum</strong><small>Hazır soru önerilerine göz at</small></span><i aria-hidden="true"/></summary><div className="template-picker-content"><label><span>Hazır sorular</span><select value={selected} onChange={event=>apply(event.target.value,event.currentTarget.form)}><option value="">{visible.length} soru arasından seç</option>{visible.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><div className="filter-chips"><button type="button" className={!category?"active":""} onClick={()=>setCategory("")}>Tümü</button>{categories.map(item=><button type="button" className={category===item?"active":""} onClick={()=>setCategory(item)} key={item}>{item}</button>)}</div></div></details>}
  <label>Bağlam<select value={scope} onChange={event=>{setScope(event.target.value as QuestionScope);setUniversityId("");}}><option value="GENERAL">Genel</option><option value="UNIVERSITY">Üniversite</option><option value="UNIVERSITY_DEPARTMENT">Üniversite + program</option></select></label>
  {scope!=="GENERAL"&&<label>Üniversite<select required value={universityId} onChange={event=>setUniversityId(event.target.value)}><option value="">Seç</option>{universities.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}
  {scope==="UNIVERSITY_DEPARTMENT"&&<label>Bölüm<select name="programId" required defaultValue={initial?.programId??""}><option value="">Seç</option>{educations.map(item=><option key={item.id} value={item.id}>{item.displayName}</option>)}</select></label>}
  <details className="question-tag-picker"><summary><span>Etiketler</span><small>{selectedTags.length?`${selectedTags.length} seçildi`:"En fazla 5 etiket seç"}</small><i aria-hidden="true"/></summary><div>{tags.length?tags.map(tag=>{const active=selectedTags.includes(tag.id),disabled=!active&&selectedTags.length>=5;return <button type="button" className={active?"active":""} aria-pressed={active} disabled={disabled} onClick={()=>setSelectedTags(current=>active?current.filter(id=>id!==tag.id):[...current,tag.id])} key={tag.id}>#{tag.name}</button>}):<p>Henüz kullanılabilir etiket yok.</p>}</div></details>
  <label>Soru başlığı<input name="title" required minLength={10} maxLength={200} defaultValue={initial?.title}/></label><label>Soru açıklaması <span className="optional-label">(isteğe bağlı)</span><textarea name="body" maxLength={5000} rows={6} defaultValue={initial?.body??""}/></label>{error&&<p className="form-error" role="alert">{error}</p>}<div className="form-actions"><button className="button" disabled={busy}>{busy?"Kaydediliyor…":initial?"Değişiklikleri kaydet":"Soruyu yayınla"}</button>{onCancel&&<button className="button secondary" type="button" onClick={onCancel}>Vazgeç</button>}</div>
 </form>;
}
