"use client";
import Link from "next/link"; import { useState, type FormEvent } from "react"; import { useRouter } from "next/navigation"; import { apiRequest } from "@/lib/client-api";
type SignedInUser = { role: string };
export function AuthForm({ mode }: { mode: "login" | "register" }) {
  const router = useRouter(); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [done, setDone] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const form = new FormData(event.currentTarget); try { await apiRequest(`/auth/${mode}`, { method: "POST", body: JSON.stringify({ email: form.get("email"), password: form.get("password") }) }); if (mode === "register") setDone(true); else { const user=await apiRequest<SignedInUser>("/me"); router.push(user.role === "MANAGER" ? "/yonetim" : "/"); router.refresh(); } } catch (reason) { setError(reason instanceof Error ? reason.message : "İşlem tamamlanamadı."); } finally { setBusy(false); } }
  if (done) return <div className="notice success" role="status"><h2>E-postanı doğrula</h2><p>Doğrulama bağlantısı gönderildi. Ardından oturum açabilirsin.</p></div>;
  return <form className="stack-form" onSubmit={submit}><label>E-posta<input required type="email" name="email" autoComplete="email"/></label><label>Parola<input required minLength={mode === "register" ? 10 : undefined} maxLength={72} type="password" name="password" autoComplete={mode === "login" ? "current-password" : "new-password"}/></label>{mode === "login" && <Link href="/parolami-unuttum">Şifremi unuttum</Link>}{error && <p className="form-error" role="alert">{error}</p>}<button className="button" disabled={busy}>{busy ? "İşleniyor…" : mode === "login" ? "Oturum aç" : "Hesap oluştur"}</button></form>;
}
