"use client";

import {useRouter} from "next/navigation";
import {useState,type FormEvent} from "react";
import {apiRequest} from "@/lib/client-api";

export function ContextContribution({universityId,programId}:{universityId:string;programId?:string}) {
  const router=useRouter();
  const [message,setMessage]=useState("");
  async function submit(path:string,method:string,payload:object,success:string){try{await apiRequest(path,{method,body:JSON.stringify(payload)});setMessage(success);router.refresh();}catch(reason){setMessage(reason instanceof Error?reason.message:"Katkı kaydedilemedi.");}}
  function metric(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);void submit("/context-metrics","PUT",{universityId,programId:programId??null,metricKey:data.get("metricKey"),value:Number(data.get("value"))},"Ölçüm kaydedildi.");}
  function experience(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);void submit("/experiences","POST",{universityId,programId:programId??null,templateType:data.get("templateType"),title:data.get("title"),body:data.get("body"),sentiment:data.get("sentiment")},"Deneyimin yayınlandı.").then(()=>form.reset());}
  function career(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);void submit("/career-outcomes","PUT",{universityId,programId,sector:data.get("sector"),firstRole:data.get("firstRole"),companyType:data.get("companyType"),graduateStudy:data.get("graduateStudy")==="on",jobSearchMonths:Number(data.get("jobSearchMonths"))},"Kariyer yolculuğun anonim istatistiğe eklendi.");}
  return <div className="contribution-grid">
    <form className="stack-form" onSubmit={metric}><h3>Gerçek hayat ölçümü ekle</h3><label>Ölçüm<select name="metricKey"><option value="WEEKLY_STUDY_HOURS">Haftalık çalışma saati</option><option value="ATTENDANCE_LEVEL">Devam zorunluluğu (%)</option><option value="PROJECT_INTENSITY">Proje yoğunluğu (%)</option><option value="EXAM_INTENSITY">Sınav yoğunluğu (%)</option><option value="ENGLISH_PERCENT">İngilizce kullanım oranı</option><option value="GROUP_WORK_PERCENT">Grup çalışması oranı</option><option value="CAMPUS_HOURS">Kampüste geçirilen saat</option><option value="MONTHLY_HOUSING_COST">Aylık barınma maliyeti</option><option value="MONTHLY_TRANSPORT_COST">Aylık ulaşım maliyeti</option><option value="MONTHLY_FOOD_COST">Aylık yemek maliyeti</option></select></label><label>Değer<input name="value" type="number" min="0" max="1000000" step="0.01" required/></label><button className="button">Kaydet</button></form>
    <form className="stack-form" onSubmit={experience}><h3>Yapılandırılmış deneyim paylaş</h3><label>Şablon<select name="templateType"><option value="WHY_I_CHOSE">Ben neden burayı seçtim?</option><option value="WISH_I_KNEW">Keşke tercih etmeden önce bilseydim</option><option value="EXPECTATION_REALITY">Beklediğim / gerçekte olan</option><option value="CHOOSE_AGAIN">Tekrar tercih eder miydim?</option></select></label><label>Görüş yönü<select name="sentiment"><option value="NEUTRAL">Bilgilendirici</option><option value="POSITIVE">Sevdiğim bir yön</option><option value="NEGATIVE">Geliştirilmesi gereken yön</option></select></label><label>Başlık<input name="title" minLength={10} maxLength={200} required/></label><label>Deneyim<textarea name="body" minLength={20} maxLength={5000} rows={5} required/></label><button className="button">Yayınla</button></form>
    {programId&&<form className="stack-form" onSubmit={career}><h3>Mezun kariyer yolculuğu</h3><label>Sektör<input name="sector" minLength={2} maxLength={120} required/></label><label>İlk rol<input name="firstRole" minLength={2} maxLength={120} required/></label><label>Şirket türü<input name="companyType" minLength={2} maxLength={80} placeholder="Startup, kamu, kurumsal…" required/></label><label>İş bulma süresi (ay)<input name="jobSearchMonths" type="number" min="0" max="120" required/></label><label className="checkbox-row"><input name="graduateStudy" type="checkbox"/> Yüksek lisans yaptım/yapıyorum</label><button className="button">Anonim katkı yap</button></form>}
    {message&&<p role="status" className="muted">{message}</p>}
  </div>;
}
