"use client";
import {useState,type FormEvent} from 'react';
import {apiRequest} from '@/lib/client-api';
import type {Experience} from '@/lib/api/decisions';
import {Button} from './ui';
import {ModalShell} from './modal-shell';
export function ExperienceActions({item,canEdit,own,after}:{item:Experience;canEdit:boolean;own:boolean;after:()=>void}) {
 const [open,setOpen]=useState<'edit'|'report'|null>(null),[body,setBody]=useState(item.body),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function share(){const url=new URL(location.href);url.searchParams.set('sekme','deneyimler');url.searchParams.set('icerik',item.id);url.hash=`content-${item.id}`;try{if(navigator.share)await navigator.share({title:item.title,url:url.toString()});else{await navigator.clipboard.writeText(url.toString());setMessage('Bağlantı kopyalandı.');}}catch(error){if(!(error instanceof DOMException&&error.name==='AbortError'))setMessage('Bağlantı paylaşılamadı.');}}
 async function submit(event:FormEvent){event.preventDefault();if(busy)return;setBusy(true);setMessage('');try{if(open==='edit')await apiRequest(`/experiences/${item.id}`,{method:'PUT',body:JSON.stringify({title:item.title,body:body.trim(),version:item.version})});else await apiRequest(`/experiences/${item.id}/reports`,{method:'POST',body:JSON.stringify({reason:reason.trim()})});setOpen(null);setMessage(open==='edit'?'Yorum güncellendi.':'Şikâyetin incelemeye gönderildi.');after();}catch(error){setMessage(error instanceof Error?error.message:'İşlem tamamlanamadı.');}finally{setBusy(false);}}
 return <div className="experience-actions"><details className="legacy-answer-menu" data-close-on-outside><summary className="legacy-answer-menu-trigger" aria-label="Deneyim işlemleri" title="Deneyim işlemleri"><svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><circle cx="5" cy="12" r="1.2"/><circle cx="12" cy="12" r="1.2"/><circle cx="19" cy="12" r="1.2"/></svg></summary><div className="legacy-answer-menu-popover"><button type="button" onClick={event=>{event.currentTarget.closest('details')?.removeAttribute('open');void share();}}>Paylaş</button>{canEdit&&<button type="button" onClick={event=>{event.currentTarget.closest('details')?.removeAttribute('open');setBody(item.body);setMessage('');setOpen('edit');}}>Düzenle</button>}{!own&&<button type="button" onClick={event=>{event.currentTarget.closest('details')?.removeAttribute('open');setMessage('');setOpen('report');}}>Şikâyet et</button>}</div></details>{message&&!open&&<span role="status" className="experience-action-status">{message}</span>}<ModalShell open={!!open} onClose={()=>setOpen(null)} title={open==='edit'?'Yorumu düzenle':'İçeriği şikâyet et'}><form className="stack-form" onSubmit={submit}>{open==='edit'?<><label>Yorum<textarea value={body} onChange={event=>setBody(event.target.value)} minLength={20} maxLength={5000} required rows={6}/></label></>:<label>Şikâyet nedeni<textarea value={reason} onChange={event=>setReason(event.target.value)} minLength={10} maxLength={1000} required/></label>}{message&&<p role="alert" className="form-error">{message}</p>}<div className="question-report-actions"><Button disabled={busy}>{busy?'Gönderiliyor…':open==='edit'?'Kaydet':'Şikâyeti gönder'}</Button><Button tone="secondary" type="button" disabled={busy} onClick={()=>setOpen(null)}>Vazgeç</Button></div></form></ModalShell></div>;
}
