"use client";
import {useEffect,useRef,useState} from "react";
import {apiRequest} from "@/lib/client-api";
import type {Experience} from "@/lib/api/decisions";
import {ContributionByline} from "./contribution-byline";
import {ContributionDialog} from "./contribution-dialog";
import {ContextContribution} from "./context-contribution";
import {ExperienceActions} from "./experience-actions";
import {Button} from "./ui";
import {experienceTemplates} from "./experience-templates";
import {Tabs} from "./ui";
export function ExperienceList({universityId,programId,currentUserId,canContribute,targetId}:{universityId:string;programId?:string;currentUserId?:string;canContribute:boolean;targetId?:string}) {
 const manuallySelected=useRef(false);
 const [target,setTarget]=useState<Experience>(),[template,setTemplate]=useState('WHY_I_CHOSE'),[items,setItems]=useState<Experience[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(0),[busy,setBusy]=useState(true),[error,setError]=useState(''),[revision,setRevision]=useState(0),[targetReady,setTargetReady]=useState(!targetId);
 useEffect(()=>{if(!targetId)return;const controller=new AbortController();setTargetReady(false);apiRequest<Experience>(`/experiences/${targetId}`,{signal:controller.signal}).then(item=>{if(controller.signal.aborted)return;if(item.universityId===universityId&&(!programId||item.programId===programId)&&experienceTemplates.some(([key])=>key===item.templateType)){setTarget(item);if(!manuallySelected.current)setTemplate(item.templateType);}}).catch(()=>undefined).finally(()=>{if(!controller.signal.aborted)setTargetReady(true);});return()=>controller.abort();},[targetId,universityId,programId]);
 useEffect(()=>{if(!targetReady)return;const controller=new AbortController();setBusy(true);setError('');const params=new URLSearchParams({universityId,templateType:template,page:String(page),size:'20'});if(programId)params.set('programId',programId);apiRequest<{items:Experience[];totalElements:number}>(`/experiences?${params}`,{signal:controller.signal}).then(data=>{if(controller.signal.aborted)return;setItems(current=>page?[...current,...data.items.filter(item=>!current.some(old=>old.id===item.id))]:data.items);setTotal(data.totalElements);}).catch(reason=>{if(!controller.signal.aborted)setError(reason instanceof Error?reason.message:'Deneyimler yüklenemedi.');}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});return()=>controller.abort();},[universityId,programId,template,page,revision,targetReady]);
 const visible=target&&target.templateType===template&&!items.some(item=>item.id===target.id)?[target,...items]:items;
 function refresh(){setPage(0);setRevision(value=>value+1);}
 return <div className="experience-panel"><div className="experience-toolbar"><Tabs className="experience-template-buttons" label="Deneyim soruları">{experienceTemplates.map(([key,label])=><button type="button" key={key} data-template={key} aria-pressed={template===key} className={template===key?"active":undefined} onClick={()=>{manuallySelected.current=true;if(template!==key){setTemplate(key);setItems([]);setPage(0);setBusy(true);}}}>{label}</button>)}</Tabs>{canContribute&&<div className="insight-actions"><ContributionDialog label="Yorum yaz"><ContextContribution universityId={universityId} programId={programId} kind="experiences" templateType={template} after={refresh}/></ContributionDialog></div>}</div>{!canContribute&&<p className="contribution-policy">Bu üniversitenin öğrencileri ve mezunları deneyim paylaşabilir.</p>}{error&&<p className="form-error" role="alert">{error} <Button tone="secondary" onClick={refresh}>Tekrar dene</Button></p>}{busy&&!items.length&&<p role="status">Yorumlar yükleniyor…</p>}<div className="experience-list">{visible.map(item=><article className={`experience-card experience-comment legacy-question-card${item.id===targetId?' notification-target':''}`} id={`content-${item.id}`} key={item.id} data-template={item.templateType}><header><ContributionByline authorId={item.authorId} authorName={item.authorName} createdAt={item.createdAt} activeAdmin={item.activeAdmin} educationStatus={item.educationStatus}/><ExperienceActions item={item} canEdit={canContribute&&item.authorId===currentUserId} own={item.authorId===currentUserId} after={refresh}/></header><span className="experience-topic">{experienceTemplates.find(([key])=>key===item.templateType)?.[1]}</span><p>{item.body}</p></article>)}</div>{!busy&&!error&&!visible.length&&<div className="empty-state"><p>Bu soruya henüz deneyim paylaşılmadı.</p></div>}{items.length<total&&items.length>0&&<Button tone="secondary" disabled={busy} onClick={()=>setPage(value=>value+1)}>{busy?'Yükleniyor…':'Daha fazla yorum'}</Button>}</div>;
}
