"use client";
import {useEffect,useState} from "react";
import {apiRequest} from "@/lib/client-api";
const keys=["users","questions","communityAnswers","adminAnswers","views","likes","applications","approvedApplications","rejectedApplications"] as const;
type Metric=typeof keys[number];type Values=Record<Metric,number>;type Point=Values&{date:string};type Analytics={dateFrom:string;dateTo:string;timezone:string;totals:Values;points:Point[]};
const colors:Record<Metric,string>={users:"#3f83c5",questions:"#7957a8",communityAnswers:"#2f8f57",adminAnswers:"#d4a72c",views:"#3f6b61",likes:"#c02f62",applications:"#687386",approvedApplications:"#2f8f57",rejectedApplications:"#bd3e4d"};
const labels:Record<Metric,string>={users:"Yeni kullanıcı",questions:"Yeni soru",communityAnswers:"Topluluk yorumu",adminAnswers:"Tanıdık yorumu",views:"Görüntülenme",likes:"Beğeni",applications:"Başvuru",approvedApplications:"Onay",rejectedApplications:"Ret"};
const groups=[{title:"Büyüme",description:"Yeni hesap ve soru üretiminin günlük seyri.",metrics:["users","questions"]},{title:"Katkılar",description:"Topluluk ve doğrulanmış Tanıdık yorumlarının karşılaştırması.",metrics:["communityAnswers","adminAnswers"]},{title:"Etkileşim",description:"Soruların aldığı görüntülenme ve beğeniler.",metrics:["views","likes"]},{title:"Tanıdık başvuruları",description:"Gönderim ve kararların günlük dağılımı.",metrics:["applications","approvedApplications","rejectedApplications"]}] satisfies {title:string;description:string;metrics:Metric[]}[];
function today(){const p=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date()),v=(t:string)=>p.find(x=>x.type===t)?.value;return `${v("year")}-${v("month")}-${v("day")}`;}function minus(date:string,days:number){const d=new Date(date+"T12:00:00Z");d.setUTCDate(d.getUTCDate()-days);return d.toISOString().slice(0,10);}
function Chart({points,metrics,title}:{points:Point[];metrics:Metric[];title:string}){const w=720,h=230,p=34,max=Math.max(1,...points.flatMap(x=>metrics.map(m=>x[m]))),x=(i:number)=>p+(points.length<2?(w-p*2)/2:i*(w-p*2)/(points.length-1)),y=(v:number)=>h-p-v*(h-p*2)/max;return <div className="analytics-chart-wrap"><svg className="analytics-chart" viewBox={`0 0 ${w} ${h}`} role="img" aria-label={`${title} grafiği; en yüksek günlük değer ${max}`}>{[0,.25,.5,.75,1].map(n=><line key={n} x1={p} x2={w-p} y1={y(max*n)} y2={y(max*n)} className="chart-grid"/>)}{metrics.map((m,i)=><g key={m}><polyline strokeDasharray={i===1?"8 5":i===2?"2 5":undefined} points={points.map((a,j)=>`${x(j)},${y(a[m])}`).join(" ")} fill="none" stroke={colors[m]} strokeWidth="3" strokeLinejoin="round" strokeLinecap="round"/>{points.length===1&&<circle cx={x(0)} cy={y(points[0][m])} r="4" fill={colors[m]}/>}</g>)}</svg><div className="chart-axis"><span>{points[0]?.date??"—"}</span><span>En yüksek {max.toLocaleString("tr-TR")}</span><span>{points.at(-1)?.date??"—"}</span></div></div>}
export function ManagerAnalytics(){const now=today(),[from,setFrom]=useState(minus(now,29)),[to,setTo]=useState(now),[range,setRange]=useState({from:minus(now,29),to:now}),[data,setData]=useState<Analytics|null>(null),[error,setError]=useState("");useEffect(()=>{let active=true;apiRequest<Analytics>(`/manager/analytics?dateFrom=${range.from}&dateTo=${range.to}`).then(v=>{if(active){setData(v);setError("");}}).catch(e=>{if(active)setError(e instanceof Error?e.message:"Grafikler yüklenemedi.");});return()=>{active=false};},[range]);function preset(days:number){const next={from:minus(now,days-1),to:now};setFrom(next.from);setTo(next.to);setData(null);setRange(next);}return <section className="management-page analytics-page"><div className="analytics-heading"><div><span className="eyebrow">RAPORLAMA</span><h1>Grafikler</h1><p>Platform hareketlerini İstanbul gün sınırlarıyla karşılaştır.</p></div><div className="analytics-presets">{[7,30,90].map(d=><button key={d} className="button button-secondary" onClick={()=>preset(d)}>Son {d} gün</button>)}</div></div><form className="auth-card analytics-filter" onSubmit={e=>{e.preventDefault();setData(null);setRange({from,to});}}><label>Başlangıç tarihi<input type="date" required value={from} max={to} onChange={e=>setFrom(e.target.value)}/></label><label>Bitiş tarihi<input type="date" required value={to} min={from} onChange={e=>setTo(e.target.value)}/></label><button className="button">Grafikleri getir</button></form>{error?<div className="auth-card"><p role="alert">{error}</p></div>:!data?<p role="status">Grafikler yükleniyor…</p>:<Content data={data}/>}</section>}
function Content({data}:{data:Analytics}){return <><div className="analytics-period"><strong>{data.dateFrom} – {data.dateTo}</strong><span>{data.points.length} gün · {data.timezone}</span></div><div className="analytics-kpis">{(["users","questions","communityAnswers","adminAnswers","views","likes"] as Metric[]).map(k=><article className="auth-card" key={k}><span>{labels[k]}</span><strong>{data.totals[k].toLocaleString("tr-TR")}</strong><small>seçili dönemde</small></article>)}</div><div className="analytics-grid">{groups.map(g=><article className="auth-card analytics-panel" key={g.title}><div><h2>{g.title}</h2><p>{g.description}</p></div><div className="chart-legend">{g.metrics.map(m=><span key={m}><i style={{background:colors[m]}}/>{labels[m]} · {data.totals[m].toLocaleString("tr-TR")}</span>)}</div><Chart points={data.points} metrics={g.metrics} title={g.title}/></article>)}</div></>}
