"use client";
import {useCallback,useEffect,useState} from "react";
import {useSearchParams} from "next/navigation";
import Link from "next/link";
import {apiRequest} from "@/lib/client-api";
import {Button,ButtonLink,Card} from "@/components/ui";
import {plainProgramName} from "@/lib/program-label";
import {promptDialog} from "@/lib/dialogs";

type View="dashboard"|"users"|"content"|"applications"|"reports"|"actions"|"analytics"|"catalog";
type Row=Record<string,unknown>;type Page={items:Row[];totalElements:number};
const endpoint={users:"/manager/users",content:"/manager/content",applications:"/manager/tanidik-applications",reports:"/manager/reports",actions:"/manager/actions",catalog:"/manager/catalog/UNIVERSITY"} as const;
const isPage=(value:Page|Row):value is Page=>Array.isArray((value as Page).items)&&typeof(value as Page).totalElements==="number";
const value=(item:Row,keys:string[])=>keys.map(key=>item[key]).find(entry=>typeof entry==="string"||typeof entry==="number");
const reason="Manager çalışma alanından doğrulanmış operasyon.";
const labels:Record<string,string>={activeAccounts:"Aktif hesap",disabledAccounts:"Pasif hesap",tanidikAccounts:"Aktif Tanıdık",pendingApplications:"Bekleyen başvuru",activeQuestions:"Aktif soru",archivedQuestions:"Arşivlenmiş soru",hiddenQuestions:"Gizlenmiş soru",communityAnswers:"Topluluk yorumu",tanidikAnswers:"Tanıdık yorumu",adminAnswers:"Tanıdık yorumu",likes:"Beğeni",detailViews:"Detay görüntülenmesi",views:"Görüntülenme",newUsers:"Yeni kullanıcı",newQuestions:"Yeni soru"};
const detailHref=(view:View,item:Row)=>view==="users"?`/yonetim/kullanicilar/${item.id}`:view==="applications"?`/yonetim/basvurular/${item.id}`:view==="actions"?`/yonetim/islemler/${item.id}`:view==="content"&&item.kind==="QUESTION"?`/yonetim/sorular/${item.id}`:null;
const text=(item:Row,key:string,fallback="—")=>typeof item[key]==="string"&&item[key]?String(item[key]):fallback;
const date=(input:unknown)=>typeof input==="string"?new Intl.DateTimeFormat("tr-TR",{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/Istanbul"}).format(new Date(input)):"—";
const authority=(input:unknown)=>input==="MEMBER"?"Üye":input==="TANIDIK"?"Tanıdık":input==="MANAGER"?"Manager":String(input??"—");
const education=(input:unknown)=>input==="YKS_ADAYI"?"YKS adayı":input==="UNIVERSITE_OGRENCISI"?"Üniversite öğrencisi":input==="MEZUN"?"Mezun":"Profil tamamlanmamış";
const normalizeRow=(item:Row):Row=>({...item,...(typeof item.departmentName==="string"?{departmentName:plainProgramName(item.departmentName)}:{})});
const normalizeData=(data:Page|Row):Page|Row=>isPage(data)?{...data,items:data.items.map(normalizeRow)}:normalizeRow(data);

export function ManagerConsole({view}:{view:View}){
 const searchParams=useSearchParams(),query=searchParams.toString();
 const[data,setData]=useState<Page|Row|null>(null),[error,setError]=useState(""),path=view==="dashboard"?"/manager/statistics":view==="analytics"?"/manager/analytics":`${endpoint[view]}?${query?`${query}&`:""}size=20`;
 const load=useCallback(()=>apiRequest<Page|Row>(path).then(result=>{setData(normalizeData(result));setError("");}).catch(cause=>setError(cause instanceof Error?cause.message:"Yönetim verisi yüklenemedi.")),[path]);useEffect(()=>{void load();},[load]);
 async function mutate(pathname:string,body:Row,method="PUT"){try{await apiRequest(pathname,{method,body:JSON.stringify(body)});await load();}catch(cause){setError(cause instanceof Error?cause.message:"İşlem kaydedilemedi.");}}
 const decide=(item:Row,status:string)=>mutate(`/manager/tanidik-applications/${item.id}/decision`,{status,reason:status==="REJECTED"?reason:null,version:item.version});
 async function toggle(item:Row){if(view==="users")await mutate(`/manager/users/${item.id}/status`,{hidden:item.deletedAt==null,version:item.version,reason});if(view==="content")await mutate(`/manager/content/${item.kind}/${item.id}/status`,{hidden:item.deletedAt==null&&item.moderatedAt==null,version:item.version,reason});if(view==="catalog")await mutate(`/manager/catalog/UNIVERSITY/${item.id}/status`,{deleted:item.deletedAt==null,version:item.version,reason});}
 const report=(item:Row,status:string)=>mutate(`/manager/reports/${item.id}`,{status,reason,version:item.version});
 async function revoke(item:Row){const operationReason=await promptDialog("Bu işlem audit geçmişine kaydedilecek.",{title:"Tanıdık statüsünü kaldır",confirmLabel:"Statüyü kaldır",tone:"danger",input:{label:"Gerekçe",minLength:10,maxLength:1000}});if(!operationReason)return;try{const detail=await apiRequest<Row>(`/manager/users/${item.id}`);if(typeof detail.activeVerificationApplicationId!=="string")throw new Error("Aktif Tanıdık doğrulaması bulunamadı.");await apiRequest(`/manager/users/${item.id}/revoke-tanidik`,{method:"POST",body:JSON.stringify({verificationId:detail.activeVerificationApplicationId,reason:operationReason})});await load();}catch(cause){setError(cause instanceof Error?cause.message:"Tanıdık statüsü kaldırılamadı.");}}
 async function editContent(item:Row){const body=await promptDialog("Yeni içerik metnini gir.",{title:"İçeriği düzenle",confirmLabel:"Devam et",input:{label:"İçerik",initialValue:String(item.body??""),minLength:2,maxLength:5000}});if(body===null)return;const operationReason=await promptDialog("Değişiklik audit geçmişine kaydedilecek.",{title:"Düzenleme gerekçesi",confirmLabel:"Kaydet",input:{label:"Gerekçe",minLength:10,maxLength:1000}});if(!operationReason)return;await mutate(`/manager/content/${item.kind}/${item.id}`,{body,version:item.version,reason:operationReason});}
 function filters(){if(!["users","content","reports"].includes(view))return null;return <form className="auth-card management-filters" method="get"><label>{view==="users"?"Ad veya e-posta":"İçerikte ara"}<input name="q" defaultValue={searchParams.get("q")??""}/></label>{view==="users"&&<><label>Yetki<select name="authority" defaultValue={searchParams.get("authority")??""}><option value="">Tümü</option><option value="MEMBER">Üye</option><option value="TANIDIK">Tanıdık</option><option value="MANAGER">Manager</option></select></label><label>Rol<select name="educationStatus" defaultValue={searchParams.get("educationStatus")??""}><option value="">Tümü</option><option value="YKS_ADAYI">YKS adayı</option><option value="UNIVERSITE_OGRENCISI">Üniversite öğrencisi</option><option value="MEZUN">Mezun</option></select></label></>}{view==="content"&&<label>İçerik türü<select name="kind" defaultValue={searchParams.get("kind")??"QUESTION"}><option value="QUESTION">Sorular</option><option value="COMMUNITY">Topluluk yorumları</option><option value="TANIDIK">Tanıdık yorumları</option></select></label>}<label>Durum<select name="status" defaultValue={searchParams.get("status")??"ALL"}><option value="ALL">Tümü</option><option value={view==="reports"?"OPEN":"VISIBLE"}>{view==="reports"?"Açık":"Görünür"}</option><option value={view==="reports"?"RESOLVED":"HIDDEN"}>{view==="reports"?"Çözüldü":"Gizlenmiş"}</option>{view==="reports"&&<option value="DISMISSED">Reddedildi</option>}</select></label><Button>Filtrele</Button>{query&&<ButtonLink tone="secondary" href={`/yonetim/${view==="users"?"kullanicilar":view==="content"?"icerik":"raporlar"}`}>Tümünü temizle</ButtonLink>}</form>}
 function card(item:Row,index:number){if(view==="users")return <Link className={`managed-user-card${item.deletedAt?" is-disabled":""}`} key={String(item.id??index)} href={`/yonetim/kullanicilar/${item.id}`}><h2>{text(item,"name",text(item,"displayName","Profil tamamlanmamış"))}</h2><p>{text(item,"email")}</p>{Boolean(item.deletedAt)&&<span className="manager-content-state is-hidden">Pasif hesap</span>}<p className="managed-user-education">{[item.universityName,item.departmentName].filter(Boolean).join(" · ")||"Eğitim bilgisi yok"}</p><dl><div><dt>Yetki</dt><dd>{authority(item.authority)}</dd></div><div><dt>Rol</dt><dd>{education(item.educationStatus)}</dd></div></dl><p>Kayıt: {date(item.createdAt)}</p><p>Son giriş: {item.lastLoginAt?date(item.lastLoginAt):"Henüz giriş yok"}</p></Link>;
  if(view==="content"){const kind=text(item,"kind","QUESTION"),questionId=text(item,"questionId",String(item.id));return <article className={`question-card manager-content-card manager-content-${kind.toLowerCase()}`} key={String(item.id??index)}><h2><Link href={`/yonetim/sorular/${questionId}`}>{text(item,"title","Başlıksız içerik")}</Link></h2><div className="manager-content-metrics"><time>{date(item.createdAt)}</time>{kind==="QUESTION"&&<span>{Number(item.viewCount??0)} görüntülenme · {Number(item.likeCount??0)} beğeni · {Number(item.communityAnswerCount??0)+Number(item.adminAnswerCount??0)} yorum</span>}</div>{kind!=="QUESTION"&&<p className="manager-comment-copy">{text(item,"body","")}</p>}<aside className="manager-content-aside"><dl className="manager-content-people"><div><dt>Soruyu soran</dt><dd>{text(item,"questionAuthorName",text(item,"authorName","Kullanıcı"))}</dd></div>{kind!=="QUESTION"&&<div><dt>Yorumu yazan</dt><dd>{text(item,"authorName","Kullanıcı")}</dd></div>}</dl><div className="manager-content-heading"><span className="manager-content-kind">{kind==="QUESTION"?"Soru":kind==="COMMUNITY"?"Topluluk yorumu":"Tanıdık yorumu"}</span><span className={`manager-content-state ${item.moderatedAt?"is-hidden":item.archivedAt?"is-archived":""}`}>{item.moderatedAt?"Manager tarafından gizlendi":item.archivedAt?"Arşivlenmiş":"Görünür"}</span></div></aside></article>}
  return <Card className={`auth-card manager-record-card manager-record-${view}`} key={String(item.id??index)}><header><span className="manager-content-kind">{view==="applications"?"Başvuru":view==="reports"?"Şikâyet":view==="actions"?"İşlem":"Kayıt"}</span>{Boolean(item.status)&&<span className={`manager-content-state ${item.status==="OPEN"||item.status==="PENDING"?"is-archived":""}`}>{String(item.status)}</span>}</header><h2>{String(value(item,["title","name","displayName","email","firstName","action","reason"])??"Kayıt")}</h2><p>{String(value(item,["body","coverLetter","reason","targetType","educationStatus"])??"")}</p><dl>{Object.entries(item).filter(([,entry])=>typeof entry==="string"||typeof entry==="number"||typeof entry==="boolean").slice(0,8).map(([key,entry])=><div key={key}><dt>{key}</dt><dd>{String(entry)}</dd></div>)}</dl>{detailHref(view,item)&&<ButtonLink tone="secondary" className="manager-detail-link" href={detailHref(view,item)!}>Ayrıntıyı aç</ButtonLink>}
   {view==="applications"&&item.status==="PENDING"&&<div className="actions"><Button tone="manager" onClick={()=>decide(item,"APPROVED")}>Onayla</Button><Button tone="secondary" onClick={()=>decide(item,"REJECTED")}>Reddet</Button></div>}
   {view==="catalog"&&<div className="actions"><Button tone="secondary" onClick={()=>toggle(item)}>{item.deletedAt?"Geri aç":"Gizle"}</Button></div>}
   {view==="reports"&&item.status==="OPEN"&&<div className="actions"><Button tone="manager" onClick={()=>report(item,"RESOLVED")}>Çözüldü</Button><Button tone="secondary" onClick={()=>report(item,"DISMISSED")}>Reddet</Button></div>}
  </Card>}
 return <div className="manager-console">{filters()}
  {error&&<p className="manager-page-error" role="alert">{error}</p>}{!data?<p role="status">Yükleniyor…</p>:isPage(data)?<><p className="answer-count">{data.totalElements} kayıt</p><div className={view==="users"?"managed-user-grid":"manager-list"}>{data.items.map(card)}</div></>:<div className="management-stats">{Object.entries(data).filter(([,entry])=>typeof entry==="number").map(([key,entry])=><Card className="auth-card manager-stat-link" key={key}><span>{labels[key]??key.replaceAll(/([A-Z])/g," $1")}</span><strong>{String(entry)}</strong><span>İncele →</span></Card>)}</div>}
 </div>;
}
