import {Button} from "./ui";
import {getAllUniversities,getCatalogCities,getUniversityDepartments} from "@/lib/api/catalog";
export type PersonalQuestionFilters=Record<string,string|undefined>;
export function questionFilterQuery(params:PersonalQuestionFilters){const result=new URLSearchParams();for(const key of ['q','scope','universityId','departmentId','tagId','city'])if(params[key])result.set(key,params[key]!);result.set('sort',params.sirala||'NEWEST');return result;}
type FilterTag={id:string;name:string};
async function filterTags():Promise<FilterTag[]>{try{const load=async(page:number)=>{const url=new URL("/api/tags",process.env.API_BASE_URL??"http://localhost:8080");url.searchParams.set("page",String(page));url.searchParams.set("size","100");const response=await fetch(url,{cache:"no-store"});if(!response.ok)throw new Error("Tag kataloğu yüklenemedi.");return await response.json() as {items?:FilterTag[];totalElements?:number};};const first=await load(0),total=typeof first.totalElements==="number"?first.totalElements:0,pages=Math.ceil(total/100),remaining=await Promise.all(Array.from({length:Math.max(0,pages-1)},(_,index)=>load(index+1))),items=[first,...remaining].flatMap(result=>Array.isArray(result.items)?result.items.filter(item=>typeof item.id==="string"&&typeof item.name==="string"):[]);return items.toSorted((a,b)=>a.name.localeCompare(b.name,"tr",{sensitivity:"base"}));}catch{return[];}}

export async function PersonalQuestionFilter({path,params,hidden={},contextLocked=false}:{path:string;params:PersonalQuestionFilters;hidden?:Record<string,string>;contextLocked?:boolean}){
 const query=params.q||'',scope=params.scope,city=params.city||'',sort=params.sirala||'NEWEST';
 const [universities,departments,tags,cities]=await Promise.all([contextLocked?Promise.resolve([]):getAllUniversities(),!contextLocked&&params.universityId?getUniversityDepartments(params.universityId):Promise.resolve([]),filterTags(),contextLocked?Promise.resolve([]):getCatalogCities().catch(()=>[])]);
 return (    <form key={JSON.stringify(params)} className="legacy-question-search" action={path} role="search">{Object.entries(hidden).map(([key,value])=><input key={key} type="hidden" name={key} value={value}/>)}<label className="sr-only" htmlFor="question-query">Soru ara</label><input id="question-query" name="q" defaultValue={query} placeholder="Soru ara"/><details data-close-on-outside><summary>Filtrele</summary><div className="legacy-filter-panel">
      {!contextLocked&&<>
      <label>Soru kapsamı<select name="scope" defaultValue={scope??""}><option value="">Tüm kapsamlar</option><option value="GENERAL">Genel</option><option value="UNIVERSITY">Üniversite</option><option value="UNIVERSITY_DEPARTMENT">Üniversite + Bölüm</option></select></label>
      <label>Üniversite<select name="universityId" defaultValue={params.universityId??""}><option value="">Tüm üniversiteler</option>{universities.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
      <label>Bölüm<select name="departmentId" defaultValue={params.departmentId??""} disabled={!params.universityId}><option value="">Tüm bölümler</option>{departments.map(item=><option key={item.id} value={item.departmentId}>{item.departmentName}</option>)}</select></label>
      </>}
      <label>Etiket<select name="tagId" defaultValue={params.tagId??""}><option value="">Tüm etiketler</option>{tags.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
      {!contextLocked&&<label>Şehir<select name="city" defaultValue={city}><option value="">Tüm şehirler</option>{cities.filter(item=>item.label!=="Belirtilmemiş").toSorted((a,b)=>a.label.localeCompare(b.label,"tr")).map(item=><option key={item.label} value={item.label}>{item.label}</option>)}</select></label>}<label>Sıralama<select name="sirala" defaultValue={sort}><option value="NEWEST">En yeni</option><option value="MOST_COMMENTED">En çok cevaplanan</option><option value="MOST_LIKED">En faydalı</option><option value="MOST_VIEWED">En çok görüntülenen</option><option value="OLDEST">En eski</option></select></label>
      <a className="legacy-filter-clear" href={Object.keys(hidden).length ? `${path}?${new URLSearchParams(hidden)}` : path}>Tümünü temizle</a>
    </div></details><Button type="submit">Ara</Button></form>);
}
