"use client";
import {useRouter} from "next/navigation";
import {useState,type FormEvent} from "react";
import {apiRequest} from "@/lib/client-api";

export function PollCreateForm({universityId,programId}:{universityId:string;programId?:string}){
 const router=useRouter(),[message,setMessage]=useState(""),[options,setOptions]=useState(["",""]);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form),values=options.map(value=>value.trim()).filter(Boolean);try{await apiRequest("/polls",{method:"POST",body:JSON.stringify({universityId,programId:programId??null,question:data.get("question"),options:values,verifiedOnly:data.get("verifiedOnly")==="on",closesAt:null})});form.reset();setOptions(["",""]);setMessage("Anket yayınlandı.");router.refresh();}catch(error){setMessage(error instanceof Error?error.message:"Anket yayınlanamadı.");}}
 return <form className="stack-form decision-form poll-create-form" onSubmit={submit}><h3>Anket oluştur</h3><label>Soru<input name="question" minLength={10} maxLength={300} required/></label><fieldset><legend>Seçenekler</legend>{options.map((value,index)=><div className="poll-option-row" key={index}><label><span>{index+1}. seçenek</span><input value={value} onChange={event=>setOptions(current=>current.map((item,itemIndex)=>itemIndex===index?event.target.value:item))} maxLength={120} required={index<2}/></label>{options.length>2&&<button type="button" aria-label={`${index+1}. seçeneği kaldır`} onClick={()=>setOptions(current=>current.filter((_,itemIndex)=>itemIndex!==index))}>×</button>}</div>)}</fieldset><button className="button secondary" type="button" disabled={options.length>=10} onClick={()=>setOptions(current=>[...current,""])}>+ Seçenek ekle</button><label className="checkbox-row"><input type="checkbox" name="verifiedOnly"/> Yalnız doğrulanmış öğrenci ve mezunlar oy versin</label><button className="button">Anketi yayınla</button>{message&&<p role="status">{message}</p>}</form>;
}
