import { readFile,mkdir } from 'node:fs/promises'
import { chromium } from '@playwright/test'
const guide=JSON.parse(await readFile(new URL('../src/features/home/guide.json',import.meta.url),'utf8'))
const escape=value=>value.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')
const html=`<!doctype html><html lang="tr"><meta charset="utf-8"><title>TanıdıkVar — Kullanım rehberi</title><style>
@page{size:A4;margin:20mm 18mm}body{font:11pt/1.6 Arial,sans-serif;color:#203e34}h1{font-size:36pt;line-height:1.1;margin:30mm 0 8mm}h2{font-size:20pt;line-height:1.25;border-bottom:2px solid #b8d59e;padding-bottom:4mm}h3{font-size:13pt}p{orphans:3;widows:3}section{break-before:page}a{color:#203e34}li{margin:3mm 0}.eyebrow{letter-spacing:2px;font-size:10pt}.summary{background:#edf3e5;padding:5mm;border-radius:3mm}.cover{break-after:page}.muted{color:#597066}h2,h3{break-after:avoid}</style>
<div class="cover"><div class="eyebrow">TANIDIKVAR · YEREL KULLANIM SÜRÜMÜ</div><h1>Sistem hakkında<br>bilmen gereken<br>her şey.</h1><p>Üniversiteyi, onu yaşayanlardan öğren.</p><p class="muted">Kullanım rehberi · 6 Eylül 2026</p><h3>İçindekiler</h3><ol>${guide.map((s,i)=>`<li><a href="#section-${i}">${escape(s.title)}</a></li>`).join('')}</ol></div>
${guide.map((s,i)=>`<section id="section-${i}"><div class="eyebrow">${String(i+1).padStart(2,'0')} / KULLANIM REHBERİ</div><h2>${escape(s.title)}</h2><p class="summary">${escape(s.summary)}</p>${s.details.map(p=>`<p>${escape(p)}</p>`).join('')}</section>`).join('')}</html>`
const browser=await chromium.launch()
try{const page=await browser.newPage();await page.setContent(html);await page.evaluate(()=>document.fonts.ready);await mkdir(new URL('../public/guides/',import.meta.url),{recursive:true});await page.pdf({path:new URL('../public/guides/tanidikvar-kullanim-rehberi.pdf',import.meta.url).pathname,format:'A4',printBackground:true,displayHeaderFooter:true,headerTemplate:'<span></span>',footerTemplate:'<div style="font:9px Arial;color:#597066;width:100%;text-align:center">TanıdıkVar · Kullanım rehberi &nbsp; <span class="pageNumber"></span> / <span class="totalPages"></span></div>'});console.log('Kullanım PDF’i oluşturuldu: 10 bölüm.')}finally{await browser.close()}
