import { useCallback } from 'react'
import { Link,useParams,useSearchParams } from 'react-router-dom'
import { AuthFormError } from '../auth/AuthFormError'
import { findActions,getActionDetail } from './workspaceApi'
import { useManagerData } from './useManagerData'
import { actionLabels } from './actionLabels'
export function ActionHistoryPage(){
 const [params,setParams]=useSearchParams(),query=params.toString(),page=Math.max(0,Number(params.get('page'))||0),loader=useCallback((signal:AbortSignal)=>findActions(query+'&size=20',signal),[query]),state=useManagerData(loader)
 function changePage(n:number){const p=new URLSearchParams(params);p.set('page',String(n));setParams(p)}
 return <section className="management-page"><h1>İşlem Geçmişi</h1><form className="auth-card management-filters" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),p=new URLSearchParams();for(const k of ['q','action','targetType']){const v=String(f.get(k)??'');if(v)p.set(k,v)}setParams(p)}}><label>İşlem, kişi veya gerekçede ara<input name="q" maxLength={100} defaultValue={params.get('q')??''}/></label><label>İşlem<select name="action" defaultValue={params.get('action')??''}><option value="">Tümü</option>{Object.entries(actionLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Kayıt türü<select name="targetType" defaultValue={params.get('targetType')??''}><option value="">Tümü</option>{['USER','ADMIN_APPLICATION','QUESTION','COMMUNITY','ADMIN','UNIVERSITY','DEPARTMENT','UNIVERSITY_DEPARTMENT','TAG'].map(v=><option key={v}>{v}</option>)}</select></label><button className="button">Filtrele</button></form>
 {state.error?<><AuthFormError error={state.error}/><button onClick={state.reload}>Tekrar dene</button></>:!state.data?<p role="status">İşlemler yükleniyor…</p>:<>{state.data.items.length===0?<p>Eşleşen işlem bulunamadı.</p>:state.data.items.map(a=><article className="question-card" key={a.id}><h2><Link to={`/manager/actions/${a.id}`}>{actionLabels[a.action]??a.action}</Link></h2><time dateTime={a.occurredAt}>{new Date(a.occurredAt).toLocaleString('tr-TR')}</time><p>{a.reason??'Bu geçmiş işlemde gerekçe kaydedilmemiş.'}</p><small>{a.targetType} · {a.targetId}</small></article>)}<nav className="pagination" aria-label="İşlem sayfaları"><button disabled={page===0} onClick={()=>changePage(page-1)}>Önceki</button><span>Sayfa {page+1} · {state.data.totalElements} işlem</span><button disabled={(page+1)*state.data.size>=state.data.totalElements} onClick={()=>changePage(page+1)}>Sonraki</button></nav></>}</section>
}
export function ActionDetailPage(){const {id=''}=useParams(),loader=useCallback((signal:AbortSignal)=>getActionDetail(id,signal),[id]),state=useManagerData(loader),a=state.data?.action;return <section className="management-page"><Link to="/manager/actions">← İşlem Geçmişi</Link><h1>İşlem detayı</h1>{state.error?<><AuthFormError error={state.error}/><button onClick={state.reload}>Tekrar dene</button></>:!a?<p role="status">İşlem yükleniyor…</p>:<article className="auth-card"><h2>{actionLabels[a.action]??a.action}</h2><dl className="account-summary"><div><dt>İşlemi yapan</dt><dd><Link to={`/manager/users/${a.actorId}`}>{state.data?.actorName}</Link></dd></div><div><dt>Zaman</dt><dd>{new Date(a.occurredAt).toLocaleString('tr-TR')}</dd></div><div><dt>Kayıt</dt><dd>{a.targetType} · {a.targetId}</dd></div><div><dt>Gerekçe</dt><dd>{a.reason??'Bu geçmiş işlemde gerekçe kaydedilmemiş.'}</dd></div></dl></article>}</section>}
