import { render,screen,fireEvent,waitFor,act } from '@testing-library/react'
import { MemoryRouter,useNavigate } from 'react-router-dom'
import { beforeEach,afterEach,expect,it,vi } from 'vitest'
import { setUser } from '../auth/authStore'
import { ManagerPage } from './ManagerPage'
const user={id:'member',email:'test@example.test',name:'Ada Yılmaz',authority:'MEMBER',educationStatus:'YKS_ADAYI',emailVerified:true,createdAt:'2026-09-05T10:00:00Z',deletedAt:null,version:0}
const content={id:'answer',kind:'COMMUNITY',questionId:'question',title:'Üniversitede yaşam nasıl?',body:'Gerçek deneyim metni',authorName:'Ada Yılmaz',deletedAt:null,moderatedAt:null,archivedAt:null,questionHidden:false,version:0}
const stats={activeUsers:12,disabledUsers:2,activeAdmins:3,pendingApplications:1,activeQuestions:10,archivedQuestions:2,hiddenQuestions:1,communityAnswers:20,adminAnswers:5,likes:100,views:15000}
const json=(v:unknown,status=200)=>new Response(JSON.stringify(v),{status})
const list=(items:unknown[],page=0,totalElements=items.length)=>json({items,page,size:20,totalElements})
beforeEach(()=>setUser({id:'manager',email:'manager@example.test',role:'MANAGER',profileCompleted:false}))
afterEach(()=>vi.unstubAllGlobals())
function show(view:'dashboard'|'users'|'content'='users',path='/manager/users'){return render(<MemoryRouter initialEntries={[path]}><ManagerPage view={view}/></MemoryRouter>)}
it('denies a regular user without requesting private data',()=>{setUser({...user,role:'YKS_ADAYI',profileCompleted:true});const fetch=vi.fn();vi.stubGlobal('fetch',fetch);show();expect(screen.getByRole('heading',{name:'Bu sayfaya erişim iznin yok.'})).toBeVisible();expect(fetch).not.toHaveBeenCalled()})
it('shows statistics and panel links with explicit view definition',async()=>{vi.stubGlobal('fetch',vi.fn(async(url:string)=>url.endsWith('/statistics')?json(stats):list([])));show('dashboard','/manager');expect(await screen.findByText('15.000')).toBeVisible();expect(screen.getByText(/tekil ziyaretçi sayısı değildir/)).toBeVisible();expect(screen.getByRole('link',{name:'Katalog'})).toHaveAttribute('href','/manager/catalog')})
it('requires a reason and sends the exact version with CSRF before disabling',async()=>{
 let disabled=false;const fetch=vi.fn(async(url:string,o:RequestInit)=>{if(url.endsWith('/csrf'))return json({token:'csrf'});if(o.method==='PUT'){disabled=true;return json({...user,deletedAt:'2026-09-06T10:00:00Z',version:1})}return list([{...user,deletedAt:disabled?'2026-09-06T10:00:00Z':null,version:disabled?1:0}])});vi.stubGlobal('fetch',fetch);show()
 fireEvent.click(await screen.findByRole('button',{name:'Hesabı pasifleştir'}));expect(screen.getByRole('button',{name:'Hesabı pasifleştir — onayla'})).toBeDisabled();fireEvent.change(screen.getByLabelText('İşlem gerekçesi'),{target:{value:'İnceleme tamamlandı.'}});fireEvent.click(screen.getByRole('button',{name:'Hesabı pasifleştir — onayla'}));await screen.findByRole('button',{name:'Hesabı geri yükle'})
 const call=fetch.mock.calls.find(([,o])=>o.method==='PUT')!;expect(JSON.parse(call[1].body as string)).toEqual({hidden:true,version:0,reason:'İnceleme tamamlandı.'});expect(new Headers(call[1].headers).get('X-XSRF-TOKEN')).toBe('csrf')
})
it('protects Manager accounts and explains restoration does not restore authority',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>list([{...user,authority:'MANAGER'}])));const view=show();await screen.findByText('Manager hesabı panelden pasifleştirilemez.');expect(screen.queryByRole('button',{name:'Hesabı pasifleştir'})).not.toBeInTheDocument();view.unmount();vi.stubGlobal('fetch',vi.fn(async()=>list([{...user,deletedAt:'2026-09-06T10:00:00Z'}])));show();fireEvent.click(await screen.findByRole('button',{name:'Hesabı geri yükle'}));expect(screen.getByText(/Eski oturumlar ve Admin yetkisi geri açılmaz/)).toBeVisible()})
it('preserves moderation reason on stale version and requires an explicit reload',async()=>{vi.stubGlobal('fetch',vi.fn(async(url:string,o:RequestInit)=>url.endsWith('/csrf')?json({token:'csrf'}):o.method==='PUT'?json({code:'STALE_VERSION',message:'Kayıt değişmiş.'},409):list([content])));show('content','/manager/content');fireEvent.click(await screen.findByRole('button',{name:'İçeriği gizle'}));fireEvent.change(screen.getByLabelText('İşlem gerekçesi'),{target:{value:'İçeriği incele.'}});fireEvent.click(screen.getByRole('button',{name:'İçeriği gizle — onayla'}));await screen.findByRole('button',{name:'Güncel listeyi yükle'});expect(screen.getByLabelText('İşlem gerekçesi')).toHaveValue('İçeriği incele.');expect(screen.queryByRole('button',{name:'İçeriği gizle — onayla'})).not.toBeInTheDocument()})
it('warns about hidden parents and owner removal when restoring moderation',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>list([{...content,deletedAt:'2026-09-06T10:00:00Z',moderatedAt:'2026-09-06T10:00:00Z',questionHidden:true}])));show('content','/manager/content');fireEvent.click(await screen.findByRole('button',{name:'İçeriği geri yükle'}));expect(screen.getByText(/Sahibinin kaldırdığı cevap ve sorunun arşiv durumu korunur/)).toBeVisible();expect(screen.queryByRole('link',{name:'Soruyu aç'})).not.toBeInTheDocument()})
it('filters on the server and resets pagination',async()=>{const fetch=vi.fn(async(_url:string)=>list([user]));vi.stubGlobal('fetch',fetch);show('users','/manager/users?page=2');await screen.findByText(user.email);fireEvent.change(screen.getByLabelText('Ad veya e-posta'),{target:{value:'isik'}});fireEvent.change(screen.getByLabelText('Görünürlük'),{target:{value:'HIDDEN'}});fireEvent.click(screen.getByRole('button',{name:'Filtrele'}));await waitFor(()=>expect(fetch.mock.calls.some(c=>String(c[0]).includes('q=isik&status=HIDDEN'))).toBe(true));expect(String(fetch.mock.calls.at(-1)?.[0])).not.toContain('page=2')})
it('does not reveal private rows after the current account changes',async()=>{let resolve:((r:Response)=>void)|undefined;vi.stubGlobal('fetch',vi.fn(()=>new Promise<Response>(r=>{resolve=r})));show();await act(async()=>setUser(null));resolve?.(list([user]));await waitFor(()=>expect(screen.queryByText(user.email)).not.toBeInTheDocument())})
it('handles retries and empty lists',async()=>{let calls=0;vi.stubGlobal('fetch',vi.fn(async()=>++calls===1?json({code:'SERVICE_UNAVAILABLE'},503):list([])));show();fireEvent.click(await screen.findByRole('button',{name:'Tekrar dene'}));expect(await screen.findByText('Eşleşen kayıt bulunamadı.')).toBeVisible()})
it('clears rows while navigating back to another filter',async()=>{let resolve:((r:Response)=>void)|undefined;vi.stubGlobal('fetch',vi.fn(async(url:string)=>url.includes('q=old')?new Promise<Response>(r=>{resolve=r}):list([user])));function Back(){const navigate=useNavigate();return <button onClick={()=>navigate(-1)}>Geri</button>}render(<MemoryRouter initialEntries={['/manager/users?q=old','/manager/users?q=new']}><Back/><ManagerPage view="users"/></MemoryRouter>);await screen.findByText(user.email);fireEvent.click(screen.getByRole('button',{name:'Geri'}));expect(screen.queryByText(user.email)).not.toBeInTheDocument();resolve?.(list([]));await screen.findByText('Eşleşen kayıt bulunamadı.')})
