import { useEffect,useState,type FormEvent } from 'react'
import { Link,useSearchParams } from 'react-router-dom'
import type { ApiError } from '../../api/apiClient'
import { AuthFormError } from '../auth/AuthFormError'
import { formError } from '../auth/formError'
import type { Page } from '../catalog/catalogApi'
import { getUsers,getContent,type ManagedUser,type ManagedContent } from './managementApi'
import { roleLabels } from '../profile/useProfileSummary'
import { questionDate } from '../questions/questionApi'
export function ManagementList({users}:{users:boolean}){
 const [params,setParams]=useSearchParams(),[data,setData]=useState<Page<ManagedUser>|Page<ManagedContent>|null>(null),[error,setError]=useState<ApiError|null>(null),[revision,setRevision]=useState(0)
 const query=params.toString(),page=Math.max(0,Number(params.get('page'))||0)
 useEffect(()=>{const c=new AbortController();const p=new URLSearchParams(query);p.set('size','20');(users?getUsers(p.toString(),c.signal):getContent(p.toString(),c.signal)).then(v=>{if(!c.signal.aborted)setData(v)}).catch(e=>{if(!c.signal.aborted)setError(formError(e))});return()=>c.abort()},[users,query,revision])
 function reload(){setData(null);setError(null);setRevision(r=>r+1)}
 function navigate(p:URLSearchParams){setData(null);setError(null);setParams(p)}
 function filter(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),p=new URLSearchParams();if(params.has('authorId'))p.set('authorId',params.get('authorId')!);for(const key of ['q','status','kind','authority','educationStatus','sort']){const v=f.get(key);if(typeof v==='string'&&v)p.set(key,v)}navigate(p)}
 function changePage(n:number){const p=new URLSearchParams(params);p.set('page',String(n));navigate(p)}
 return <><p>{users?'Pasifleştirme tüm oturumları kapatır, Admin yetkisini kaldırır ve bekleyen başvuruları reddeder. İçerikler korunur.':'Soru veya yorumun bağlamını ve işlem seçeneklerini detay ekranından inceleyin.'}</p>
 {!users&&params.has('authorId')&&<p className="archive-notice">Seçilen kullanıcının katkıları gösteriliyor. <Link to={'/manager/users/'+encodeURIComponent(params.get('authorId')!)}>Kullanıcıya dön</Link> <button type="button" onClick={()=>{const p=new URLSearchParams(params);p.delete('authorId');p.delete('page');navigate(p)}}>Kullanıcı filtresini kaldır</button></p>}
 <form key={query} className="auth-card management-filters" onSubmit={filter}><label>{users?'Ad veya e-posta':'İçerikte ara'}<input name="q" defaultValue={params.get('q')??''} maxLength={100}/></label>
 {!users&&<label>İçerik türü<select name="kind" defaultValue={params.get('kind')??'QUESTION'}><option value="QUESTION">Sorular</option><option value="COMMUNITY">Topluluk yorumları</option><option value="ADMIN">Admin yorumları</option></select></label>}
 {users&&<label>Yetki<select name="authority" defaultValue={params.get('authority')??''}><option value="">Tümü</option><option value="MEMBER">Üye</option><option value="ADMIN">Admin</option><option value="MANAGER">Manager</option></select></label>}
 {users&&<label>Rol<select name="educationStatus" defaultValue={params.get('educationStatus')??''}><option value="">Tümü</option><option value="YKS_ADAYI">YKS adayı</option><option value="UNIVERSITE_OGRENCISI">Üniversite öğrencisi</option><option value="MEZUN">Mezun</option></select></label>}{users&&<label>Sırala<select name="sort" defaultValue={params.get('sort')??'CREATED_DESC'}><option value="CREATED_DESC">Kayıt: yeniden eskiye</option><option value="CREATED_ASC">Kayıt: eskiden yeniye</option><option value="LAST_LOGIN_DESC">Son giriş: yeniden eskiye</option><option value="LAST_LOGIN_ASC">Son giriş: eskiden yeniye</option></select></label>}
 <label>Görünürlük<select name="status" defaultValue={params.get('status')??'ALL'}><option value="ALL">Tümü</option><option value="VISIBLE">{users?'Aktif hesaplar':'Görünür içerikler'}</option><option value="HIDDEN">{users?'Pasif hesaplar':'Manager tarafından gizlenenler'}</option></select></label><button className="button">Filtrele</button>{query&&<button type="button" className="button button-secondary" onClick={()=>navigate(new URLSearchParams())}>Tümünü temizle</button>}</form>
 {error?<div className="auth-card"><AuthFormError error={error}/><button onClick={reload}>Tekrar dene</button></div>:!data?<p role="status">Liste yükleniyor…</p>:<>
 {data.items.length===0?<p>Eşleşen kayıt bulunamadı.</p>:users?<div className="managed-user-grid">{(data.items as ManagedUser[]).map(a=><Link className={`managed-user-card ${a.deletedAt?'is-disabled':''}`} key={a.id+'-'+a.version} to={'/manager/users/'+a.id}><h2>{a.name??'Profil tamamlanmamış'}</h2><p>{a.email}</p>{a.deletedAt&&<span className="status-badge status-pending">Pasif hesap</span>}<p className="managed-user-education">{a.universityName??'Üniversite bilgisi yok'}{a.departmentName&&` · ${a.departmentName}`}</p><dl><div><dt>Yetki</dt><dd>{a.authority==='MEMBER'?'Üye':a.authority}</dd></div><div><dt>Rol</dt><dd>{roleLabels[a.educationStatus??'USER']??'Profil tamamlanmamış'}</dd></div></dl><p>Kayıt: {questionDate(a.createdAt)}</p><p>Son giriş: {a.lastLoginAt?questionDate(a.lastLoginAt):'Henüz giriş yok'}</p></Link>)}</div>:(data.items as ManagedContent[]).map(a=><article className="question-card manager-content-card" key={a.id+'-'+a.version}><h2>{a.title}</h2><p>{a.authorName} · {a.moderatedAt?'Manager tarafından gizlendi':a.deletedAt?'Sahibi kaldırdı':'Görünür'}{a.archivedAt?' · Soru arşivlenmiş':''}</p><p className="manager-question-metrics">{questionDate(a.createdAt)}{a.kind==='QUESTION'&&<> · {a.viewCount} görüntülenme · {a.likeCount} beğeni · {a.communityAnswerCount+a.adminAnswerCount} yorum</>}</p>{a.questionHidden&&<p>Bağlı soru gizlenmiş; yorum herkese kapalı.</p>}<p className="answer-body">{a.body}</p><Link className="button button-info manager-content-detail" to={'/manager/questions/'+a.questionId}>Detay</Link></article>)}
 <nav className="answer-actions" aria-label="Yönetim listesi sayfaları"><button disabled={page===0} onClick={()=>changePage(page-1)}>Önceki</button><span>Sayfa {page+1} · {data.totalElements} kayıt</span><button disabled={(page+1)*data.size>=data.totalElements} onClick={()=>changePage(page+1)}>Sonraki</button></nav></>}
 </>
}
