import { render,screen,fireEvent,waitFor,act } from '@testing-library/react'
import { MemoryRouter,useNavigate } from 'react-router-dom'
import { beforeEach,afterEach,expect,it,vi } from 'vitest'
import { setUser } from '../auth/authStore'
import { ManagerPage } from './ManagerPage'
const user={id:'member',email:'test@example.test',name:'Ada Yılmaz',authority:'MEMBER',educationStatus:'YKS_ADAYI',universityName:null,departmentName:null,emailVerified:true,createdAt:'2026-09-05T10:00:00Z',deletedAt:null,version:0}
const content={id:'answer',kind:'COMMUNITY',questionId:'question',authorId:'member',title:'Üniversitede yaşam nasıl?',body:'Gerçek deneyim metni',authorName:'Ada Yılmaz',createdAt:'2026-09-05T10:00:00Z',deletedAt:null,moderatedAt:null,archivedAt:null,questionHidden:false,viewCount:1,likeCount:2,communityAnswerCount:3,adminAnswerCount:0,version:0}
const stats={activeUsers:12,disabledUsers:2,activeAdmins:3,pendingApplications:1,activeQuestions:10,archivedQuestions:2,hiddenQuestions:1,communityAnswers:20,adminAnswers:5,likes:100,views:15000}
const json=(v:unknown,status=200)=>new Response(JSON.stringify(v),{status})
const list=(items:unknown[],page=0,totalElements=items.length)=>json({items,page,size:20,totalElements})
beforeEach(()=>setUser({id:'manager',email:'manager@example.test',role:'MANAGER',profileCompleted:false}))
afterEach(()=>vi.unstubAllGlobals())
function show(view:'dashboard'|'users'|'content'='users',path='/manager/users'){return render(<MemoryRouter initialEntries={[path]}><ManagerPage view={view}/></MemoryRouter>)}
it('denies a regular user without requesting private data',()=>{setUser({...user,role:'YKS_ADAYI',profileCompleted:true});const fetch=vi.fn();vi.stubGlobal('fetch',fetch);show();expect(screen.getByRole('heading',{name:'Bu sayfaya erişim iznin yok.'})).toBeVisible();expect(fetch).not.toHaveBeenCalled()})
it('shows all statistics as panel links',async()=>{vi.stubGlobal('fetch',vi.fn(async(url:string)=>url.endsWith('/statistics')?json(stats):list([])));show('dashboard','/manager');expect(await screen.findByText('12')).toBeVisible();expect(screen.getByText('15.000')).toBeVisible();expect(screen.getByRole('link',{name:/Bekleyen başvuru/})).toHaveAttribute('href','/manager/applications');expect(screen.getByRole('link',{name:/Detay görüntülenmesi/})).toHaveAttribute('href','/manager/content?kind=QUESTION&status=ALL')})
it('shows compact cards with role filtering and opens the user detail',async()=>{const fetch=vi.fn(async(_url:string)=>list([user]));vi.stubGlobal('fetch',fetch);show();const card=await screen.findByRole('link',{name:/Ada Yılmaz/});expect(card).toHaveAttribute('href','/manager/users/member');expect(screen.getByText('YKS Adayı')).toBeVisible();expect(screen.queryByText('E-posta doğrulanmış')).not.toBeInTheDocument();fireEvent.change(screen.getByLabelText('Rol'),{target:{value:'YKS_ADAYI'}});fireEvent.click(screen.getByRole('button',{name:'Filtrele'}));await waitFor(()=>expect(fetch.mock.calls.some(c=>String(c[0]).includes('educationStatus=YKS_ADAYI'))).toBe(true))})
it('shows only a colored detail link for content moderation',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>list([content])));show('content','/manager/content');expect((await screen.findByRole('link',{name:'Detay'})).getAttribute('href')).toBe('/manager/questions/question');expect(screen.queryByRole('button',{name:/İçeriği/})).not.toBeInTheDocument();expect(screen.queryByRole('link',{name:'Soruyu aç'})).not.toBeInTheDocument()})
it('filters on the server and resets pagination',async()=>{const fetch=vi.fn(async(_url:string)=>list([user]));vi.stubGlobal('fetch',fetch);show('users','/manager/users?page=2');await screen.findByText(user.email);fireEvent.change(screen.getByLabelText('Ad veya e-posta'),{target:{value:'isik'}});fireEvent.change(screen.getByLabelText('Görünürlük'),{target:{value:'HIDDEN'}});fireEvent.click(screen.getByRole('button',{name:'Filtrele'}));await waitFor(()=>expect(fetch.mock.calls.some(c=>String(c[0]).includes('q=isik&status=HIDDEN'))).toBe(true));expect(String(fetch.mock.calls.at(-1)?.[0])).not.toContain('page=2')})
it('does not reveal private rows after the current account changes',async()=>{let resolve:((r:Response)=>void)|undefined;vi.stubGlobal('fetch',vi.fn(()=>new Promise<Response>(r=>{resolve=r})));show();await act(async()=>setUser(null));resolve?.(list([user]));await waitFor(()=>expect(screen.queryByText(user.email)).not.toBeInTheDocument())})
it('handles retries and empty lists',async()=>{let calls=0;vi.stubGlobal('fetch',vi.fn(async()=>++calls===1?json({code:'SERVICE_UNAVAILABLE'},503):list([])));show();fireEvent.click(await screen.findByRole('button',{name:'Tekrar dene'}));expect(await screen.findByText('Eşleşen kayıt bulunamadı.')).toBeVisible()})
it('clears rows while navigating back to another filter',async()=>{let resolve:((r:Response)=>void)|undefined;vi.stubGlobal('fetch',vi.fn(async(url:string)=>url.includes('q=old')?new Promise<Response>(r=>{resolve=r}):list([user])));function Back(){const navigate=useNavigate();return <button onClick={()=>navigate(-1)}>Geri</button>}render(<MemoryRouter initialEntries={['/manager/users?q=old','/manager/users?q=new']}><Back/><ManagerPage view="users"/></MemoryRouter>);await screen.findByText(user.email);fireEvent.click(screen.getByRole('button',{name:'Geri'}));expect(screen.queryByText(user.email)).not.toBeInTheDocument();resolve?.(list([]));await screen.findByText('Eşleşen kayıt bulunamadı.')})
