import { useCallback,useEffect,useRef,useState } from 'react'
import { Link,useParams } from 'react-router-dom'
import { AuthFormError } from '../auth/AuthFormError'
import { formError } from '../auth/formError'
import type { ApiError } from '../../api/apiClient'
import { RemotePicker } from '../catalog/RemotePicker'
import { getCatalog,type Choice } from '../catalog/catalogApi'
import { getQuestionReview,saveClassification,type Classification } from './workspaceApi'
import { useManagerData } from './useManagerData'
import { ManagementDecision } from './ManagementDecision'
import { contentStatus,type ManagedContent } from './managementApi'
export function QuestionReviewPage(){
 const {id=''}=useParams(),[page,setPage]=useState(0),loader=useCallback((signal:AbortSignal)=>getQuestionReview(id,page,signal),[id,page]),state=useManagerData(loader),d=state.data
 return <section className="management-page"><Link to="/manager/content">← Sorular ve Cevaplar</Link><h1>Soru ve cevap incelemesi</h1>{state.error?<><AuthFormError error={state.error}/><button onClick={state.reload}>Tekrar dene</button></>:!d?<p role="status">İçerik yükleniyor…</p>:<><ModeratedRecord key={d.question.version} content={d.question} reload={state.reload}/><ClassificationEditor key={'classification-'+d.classification.version} id={id} initial={d.classification} reload={state.reload}/><h2>Cevaplar</h2>{d.answers.items.length===0?<p>Bu soruda cevap bulunmuyor.</p>:d.answers.items.map(a=><ModeratedRecord key={a.id+'-'+a.version} content={a} reload={state.reload}/>)}<nav className="pagination" aria-label="Moderasyon cevap sayfaları"><button disabled={page===0} onClick={()=>setPage(page-1)}>Önceki</button><span>Sayfa {page+1} · {d.answers.totalElements} cevap</span><button disabled={(page+1)*d.answers.size>=d.answers.totalElements} onClick={()=>setPage(page+1)}>Sonraki</button></nav></>}</section>
}
function ModeratedRecord({content:a,reload}:{content:ManagedContent;reload:()=>void}){return <article className="question-card"><span className="eyebrow">{a.kind==='QUESTION'?'Soru':a.kind==='ADMIN'?'Admin cevabı':'Topluluk cevabı'}</span>{a.kind==='QUESTION'&&<h2>{a.title}</h2>}<p>{a.authorName} · {a.moderatedAt?'Manager tarafından gizlendi':a.deletedAt?'Sahibi kaldırdı':'Görünür'}{a.archivedAt?' · Soru arşivlenmiş':''}</p>{a.questionHidden&&<p>Bağlı soru gizli; bu cevap herkese kapalı.</p>}<p className="answer-body">{a.body}</p><ManagementDecision label={a.moderatedAt?'İçeriği geri yükle':'İçeriği gizle'} explanation={a.moderatedAt?'Yalnız Manager gizlemesi kaldırılır. Sahibinin kaldırması ve soru arşivi korunur.':'İçerik herkese açık ekranlardan gizlenir. Metin, ilk yayın ve geçmiş kayıtları korunur.'} apply={reason=>contentStatus(a,reason)} reload={reload}/></article>}
function ClassificationEditor({id,initial,reload}:{id:string;initial:Classification;reload:()=>void}){
 const [scope,setScope]=useState(initial.scope),[university,setUniversity]=useState<Choice|null>(initial.universityId?{id:initial.universityId,label:'Mevcut üniversite'}:initial.education?{id:initial.education.universityId,label:initial.education.universityName}:null),[department,setDepartment]=useState<Choice|null>(initial.education?{id:initial.education.id,label:initial.education.departmentName}:null),[tags,setTags]=useState<Choice[]>(initial.tagIds.map(id=>({id,label:'Mevcut tag'}))),[reason,setReason]=useState(''),[error,setError]=useState<ApiError|null>(null),[pending,setPending]=useState(false),busy=useRef(false)
 useEffect(()=>{const c=new AbortController();async function names(){let page=0;const choices:Choice[]=[];while(true){const d=await getCatalog(`/api/manager/catalog/TAG?includeDeleted=true&size=100&page=${page++}`,c.signal);choices.push(...d.items.map(t=>({id:t.id,label:t.name})));if(page*d.size>=d.totalElements||!d.items.length)break}if(!c.signal.aborted)setTags(t=>t.map(tag=>choices.find(c=>c.id===tag.id)??tag))}void names().catch(e=>{if(!c.signal.aborted)setError(formError(e))});return()=>c.abort()},[])
 async function save(){if(busy.current)return;busy.current=true;setPending(true);setError(null);try{await saveClassification(id,{scope,universityId:scope==='UNIVERSITY'?university?.id??null:null,universityDepartmentId:scope==='UNIVERSITY_DEPARTMENT'?department?.id??null:null,tagIds:tags.map(t=>t.id),version:initial.version},reason.trim());reload()}catch(e){setError(formError(e))}finally{busy.current=false;setPending(false)}}
 return <form className="auth-card" onSubmit={e=>{e.preventDefault();void save()}}><h2>Kapsam ve tag düzeltmesi</h2><fieldset disabled={pending}><legend>Sınıflandırma</legend><label htmlFor="review-scope">Soru kapsamı</label><select id="review-scope" value={scope} onChange={e=>setScope(e.target.value as Classification['scope'])}><option value="GENERAL">Genel</option><option value="UNIVERSITY">Üniversite</option><option value="UNIVERSITY_DEPARTMENT">Üniversite + Bölüm</option></select>{scope!=='GENERAL'&&<div className="form-columns"><RemotePicker label="Üniversite" endpoint="/api/universities" value={university} onChange={v=>{setUniversity(v);setDepartment(null)}}/>{scope==='UNIVERSITY_DEPARTMENT'&&<RemotePicker key={university?.id??'none'} label="Bölüm" endpoint={`/api/universities/${university?.id}/departments`} education value={department} disabled={!university} onChange={setDepartment}/>}</div>}<RemotePicker label="Tag ekle" endpoint="/api/tags" value={null} disabled={tags.length>=5} onChange={v=>{if(v&&!tags.some(t=>t.id===v.id))setTags([...tags,v])}}/><div className="answer-actions">{tags.map(t=><button type="button" key={t.id} onClick={()=>setTags(tags.filter(x=>x.id!==t.id))}>{t.label} · Kaldır</button>)}</div><label htmlFor="classification-reason">Düzeltme gerekçesi</label><textarea id="classification-reason" required maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></fieldset><AuthFormError error={error}/>{error?.code==='STALE_VERSION'?<button type="button" onClick={reload}>Güncel soruyu yükle</button>:<button className="button" disabled={pending||!reason.trim()}>{pending?'Kaydediliyor…':'Sınıflandırmayı kaydet'}</button>}</form>
}
