import { useEffect,useState,type FormEvent } from 'react'
import { Link,useSearchParams } from 'react-router-dom'
import { apiGet,apiMutation,isRecord,type ApiError } from '../../api/apiClient'
import { AuthFormError } from '../auth/AuthFormError'
import { formError } from '../auth/formError'
import { pageOf,type Page } from '../catalog/catalogApi'
import { questionDate } from '../questions/questionApi'

type Report={id:string;questionId:string;questionTitle:string;questionAuthorId?:string|null;questionAuthorName?:string;reporterId:string;reporterName:string;reason:string;status:string;createdAt:string;reviewedAt?:string|null;resolutionReason?:string|null;version:number}
const statusLabels:Record<string,string>={OPEN:'İnceleme bekliyor',RESOLVED:'Çözüldü',DISMISSED:'İhlal bulunamadı'}
function parse(v:unknown):Report{if(!isRecord(v)||!['id','questionId','questionTitle','reporterId','reporterName','reason','status','createdAt'].every(k=>typeof v[k]==='string')||v.questionAuthorId!==undefined&&v.questionAuthorId!==null&&typeof v.questionAuthorId!=='string'||v.questionAuthorName!==undefined&&typeof v.questionAuthorName!=='string'||typeof v.version!=='number')throw new Error('Şikâyet verisi geçersiz');return v as unknown as Report}

export function ReportsPage(){
 const [params,setParams]=useSearchParams(),[data,setData]=useState<Page<Report>|null>(null),[revision,setRevision]=useState(0),[error,setError]=useState<ApiError|null>(null),[pendingId,setPendingId]=useState('')
 const query=params.toString(),page=Math.max(0,Number(params.get('page'))||0)
 useEffect(()=>{const c=new AbortController();apiGet(`/api/manager/reports?${query}`,c.signal).then(v=>{if(!c.signal.aborted)setData(pageOf(v,parse))}).catch(e=>{if(!c.signal.aborted)setError(formError(e))});return()=>c.abort()},[query,revision])
 function filter(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),p=new URLSearchParams();for(const k of ['q','status','sort']){const v=f.get(k);if(typeof v==='string'&&v)p.set(k,v)}setData(null);setError(null);setParams(p)}
 function changePage(next:number){const p=new URLSearchParams(params);p.set('page',String(next));setData(null);setError(null);setParams(p)}
 async function decide(r:Report,status:'RESOLVED'|'DISMISSED'){setPendingId(r.id);setError(null);try{await apiMutation(`/api/manager/reports/${r.id}`,'PUT',{status,reason:status==='RESOLVED'?'Şikâyet incelendi ve gerekli işlem uygulandı.':'İncelemede topluluk kurallarını ihlal eden bir durum bulunamadı.',version:r.version});setRevision(x=>x+1)}catch(e){setError(formError(e))}finally{setPendingId('')}}
 return <section className="management-page manager-reports-page"><h1>Şikâyetler</h1><p>Şikâyet edilen soruyu, soru sahibini ve bildirimi yapan kişiyi aynı kayıtta inceleyin.</p>
  <form className="auth-card management-filters" onSubmit={filter}><label>Ara<input name="q" defaultValue={params.get('q')??''}/></label><label>Durum<select name="status" defaultValue={params.get('status')??''}><option value="">Tümü</option><option value="OPEN">Açık</option><option value="RESOLVED">Çözüldü</option><option value="DISMISSED">Reddedildi</option></select></label><label>Sırala<select name="sort" defaultValue={params.get('sort')??'NEWEST'}><option value="NEWEST">En yeni</option><option value="OLDEST">En eski</option><option value="STATUS">Durum</option></select></label><button className="button">Uygula</button></form>
  {error&&<div className="manager-page-error"><AuthFormError error={error}/><button type="button" onClick={()=>{setError(null);setRevision(x=>x+1)}}>Tekrar dene</button></div>}
  {!data?<p role="status">Şikâyetler yükleniyor…</p>:data.items.length===0?<div className="auth-card manager-empty-state">Eşleşen şikâyet bulunamadı.</div>:<div className="manager-report-list">{data.items.map(r=><article className={`auth-card manager-report-card report-${r.status.toLowerCase()}`} key={r.id}><header><span className="manager-report-status">{statusLabels[r.status]??r.status}</span><time dateTime={r.createdAt}>{questionDate(r.createdAt)}</time></header><h2><Link to={`/manager/questions/${r.questionId}`}>{r.questionTitle}</Link></h2><dl className="manager-report-people"><div><dt>Soruyu soran</dt><dd>{r.questionAuthorId?<Link to={`/manager/users/${r.questionAuthorId}`}>{r.questionAuthorName??'Kullanıcı'}</Link>:r.questionAuthorName??'Kullanıcı bilgisi yok'}</dd></div><div><dt>Şikâyet eden</dt><dd><Link to={`/manager/users/${r.reporterId}`}>{r.reporterName}</Link></dd></div></dl><section className="manager-report-reason"><h3>Şikâyet nedeni</h3><p>{r.reason}</p></section>{r.resolutionReason&&<p className="manager-report-resolution"><strong>İnceleme sonucu:</strong> {r.resolutionReason}</p>}{r.status==='OPEN'&&<div className="manager-report-actions"><Link className="button button-info" to={`/manager/questions/${r.questionId}`}>Soruyu incele</Link><button className="button button-success" disabled={pendingId===r.id} onClick={()=>void decide(r,'RESOLVED')}>Çözüldü</button><button className="button button-danger" disabled={pendingId===r.id} onClick={()=>void decide(r,'DISMISSED')}>İhlal yok</button></div>}</article>)}</div>}
  {data&&<nav className="pagination" aria-label="Şikâyet sayfaları"><button disabled={page===0} onClick={()=>changePage(page-1)}>Önceki</button><span>Sayfa {page+1} · {data.totalElements} şikâyet</span><button disabled={(page+1)*data.size>=data.totalElements} onClick={()=>changePage(page+1)}>Sonraki</button></nav>}
 </section>
}
