import { useCallback,useEffect,useState } from 'react'
import { Link,useParams } from 'react-router-dom'
import { apiGet,apiMutation,ApiError } from '../../api/apiClient'
import { AuthFormError } from '../auth/AuthFormError'
import { formError } from '../auth/formError'
import { ApplicationCard } from '../applications/ApplicationCard'
import { getApplication,getUserApplications,getUserDetail } from './workspaceApi'
import { useManagerData } from './useManagerData'
import { ManagementDecision } from './ManagementDecision'
import { userStatus } from './managementApi'
import { roleLabels } from '../profile/useProfileSummary'
export function ApplicationReviewPage(){
 const {id=''}=useParams(),loader=useCallback((signal:AbortSignal)=>getApplication(id,signal),[id]),state=useManagerData(loader)
 return <section className="management-page"><Link to="/manager/applications">← Başvurular</Link><h1>Başvuru incelemesi</h1>{state.error?<><AuthFormError error={state.error}/><button onClick={state.reload}>Tekrar dene</button></>:!state.data?<p role="status">Başvuru yükleniyor…</p>:<><Link to={`/manager/users/${state.data.applicantId}`}>Kullanıcı detayını aç</Link><div className="application-review-grid"><ApplicationCard key={state.data.version+'-'+state.data.activeVerification} application={state.data} manager reload={state.reload}/><DocumentPreview key={state.data.documentFileId} id={state.data.documentFileId}/></div><ApplicationHistory key={state.data.id+'-'+state.data.version+'-'+state.data.activeVerification} userId={state.data.applicantId}/></>}</section>
}
function DocumentPreview({id}:{id:string}){
 const [url,setUrl]=useState<string|null>(null),[error,setError]=useState<ApiError|null>(null),[revision,setRevision]=useState(0)
 useEffect(()=>{const c=new AbortController();let objectUrl:string|undefined;apiGet(`/api/files/${id}/download`,c.signal,true).then(v=>{if(c.signal.aborted)return;if(!(v instanceof Blob))throw new ApiError(200,'INVALID_RESPONSE','Belge görüntülenemedi.');objectUrl=URL.createObjectURL(new Blob([v],{type:'application/pdf'}));setUrl(objectUrl)}).catch(e=>{if(!c.signal.aborted)setError(formError(e))});return()=>{c.abort();if(objectUrl)URL.revokeObjectURL(objectUrl)}},[id,revision])
 return <section className="auth-card document-preview"><h2>Gönderilen belge</h2>{error?<><AuthFormError error={error}/><button onClick={()=>{setError(null);setRevision(r=>r+1)}}>Belgeyi yeniden yükle</button></>:url?<><iframe title="Başvuru belgesi" src={url}/><a href={url} download="belge.pdf">PDF görüntülenmiyorsa indir</a></>:<p role="status">Belge yükleniyor…</p>}</section>
}
export function ApplicationHistory({userId}:{userId:string}){
 const [page,setPage]=useState(0),loader=useCallback((signal:AbortSignal)=>getUserApplications(userId,page,signal),[userId,page]),state=useManagerData(loader)
 return <section className="auth-card"><h2>Başvuru geçmişi</h2>{state.error?<><AuthFormError error={state.error}/><button onClick={state.reload}>Tekrar dene</button></>:!state.data?<p role="status">Geçmiş yükleniyor…</p>:<>{state.data.items.length===0?<p>Başvuru bulunmuyor.</p>:<ul className="manager-record-list">{state.data.items.map(a=><li key={a.id}><Link to={`/manager/applications/${a.id}`}>{new Date(a.submittedAt).toLocaleString('tr-TR')} · {a.status==='PENDING'?'Bekleyen':a.status==='APPROVED'?'Onaylanan':'Reddedilen'}</Link><span>{a.universityName} · {a.departmentName}</span>{a.rejectionReason&&<p>{a.rejectionReason}</p>}</li>)}</ul>}<nav className="pagination" aria-label="Kullanıcı başvuru sayfaları"><button disabled={page===0} onClick={()=>setPage(page-1)}>Önceki</button><span>Sayfa {page+1} · {state.data.totalElements} başvuru</span><button disabled={(page+1)*state.data.size>=state.data.totalElements} onClick={()=>setPage(page+1)}>Sonraki</button></nav></>}</section>
}
export function UserDetailPage(){
 const {id=''}=useParams(),loader=useCallback((signal:AbortSignal)=>getUserDetail(id,signal),[id]),state=useManagerData(loader),d=state.data,u=d?.user
 return <section className="management-page"><Link to="/manager/users">← Kullanıcılar</Link><h1>Kullanıcı detayı</h1>{state.error?<><AuthFormError error={state.error}/><button onClick={state.reload}>Tekrar dene</button></>:!d||!u?<p role="status">Kullanıcı yükleniyor…</p>:<><div className="auth-card"><h2>{u.name??'Ad-soyad belirtilmemiş'}</h2><dl className="account-summary"><div><dt>E-posta</dt><dd>{u.email}</dd></div><div><dt>Eğitim durumu</dt><dd>{roleLabels[u.educationStatus??'USER']??u.educationStatus}</dd></div><div><dt>Üniversite / bölüm</dt><dd>{d.universityName??'—'} / {d.departmentName??'—'}{d.graduationYear?` · ${d.graduationYear}`:''}</dd></div><div><dt>Hesap durumu</dt><dd>{u.deletedAt?'Pasif':'Aktif'}</dd></div><div><dt>E-posta doğrulama</dt><dd>{u.emailVerified?'Doğrulanmış':'Doğrulanmamış'}</dd></div><div><dt>Yönetim yetkisi</dt><dd>{u.authority==='MEMBER'?'Üye':u.authority}</dd></div><div><dt>Belge doğrulaması</dt><dd>{d.verificationId?<Link to={`/manager/applications/${d.verificationId}`}>Aktif onayı incele</Link>:'Aktif Admin doğrulaması yok'}</dd></div></dl><p>Geçmiş kayıtlar dahil: {d.questions} soru · {d.communityAnswers} topluluk cevabı · {d.adminAnswers} Admin cevabı</p>
 {u.authority==='MANAGER'?<p>Manager hesapları pasifleştirilemez.</p>:<div className="manager-detail-actions"><ManagementDecision label={u.deletedAt?'Hesabı geri yükle':'Hesabı pasifleştir'} explanation={u.deletedAt?'Yeni giriş yapılabilir; önceki Admin yetkisi geri verilmez.':'Oturumlar kapatılır, Admin yetkisi kaldırılır ve bekleyen başvurular reddedilir. İçerikler korunur.'} apply={reason=>userStatus(u,reason)} reload={state.reload}/>{u.authority==='ADMIN'&&d.verificationId&&<ManagementDecision label="Admin yetkisini kaldır" explanation="Geçmiş onaylar ve cevaplar korunur. Bekleyen yeniden doğrulama başvuruları reddedilir." apply={reason=>apiMutation(`/api/manager/users/${u.id}/revoke-admin`,'POST',{verificationId:d.verificationId,reason})} reload={state.reload}/>}</div>}</div><ApplicationHistory key={u.version+'-'+d.verificationId} userId={id}/></>}</section>
}
