import {CompareForm} from "@/components/compare-form";
import {getCatalogProgram,getUniversity,type AdmissionOption,type AdmissionStatistics,type ProgramDetail} from "@/lib/api/catalog";

export const metadata={title:"Üniversite veya program karşılaştır",description:"Programları aynı yıldaki başarı sırası, puan, kontenjan ve akademik kadroyla karşılaştır.",alternates:{canonical:"/karsilastir"}};
async function side(id?:string,programId?:string){if(!id)return null;try{return{university:await getUniversity(id),program:programId?await getCatalogProgram(programId):null};}catch{return null;}}
type Params={mode?:string;year?:string;u1?:string;u2?:string;u3?:string;p1?:string;p2?:string;p3?:string;left?:string;right?:string;leftProgram?:string;rightProgram?:string};
type Entry=NonNullable<Awaited<ReturnType<typeof side>>>;
const format=(value:number|null|undefined,digits=0)=>value?.toLocaleString("tr-TR",{maximumFractionDigits:digits})??"Veri yok";
const netFields:{key:keyof AdmissionStatistics;label:string}[]=[
  {key:"averageSecondaryScore",label:"Diploma notu"},{key:"tytTurkishNet",label:"TYT Türkçe"},{key:"tytSocialNet",label:"TYT Sosyal"},{key:"tytMathNet",label:"TYT Matematik"},{key:"tytScienceNet",label:"TYT Fen"},{key:"aytMathNet",label:"AYT Matematik"},{key:"aytPhysicsNet",label:"AYT Fizik"},{key:"aytChemistryNet",label:"AYT Kimya"},{key:"aytBiologyNet",label:"AYT Biyoloji"},{key:"aytLiteratureNet",label:"AYT Edebiyat"},{key:"aytHistory1Net",label:"AYT Tarih-1"},{key:"aytGeography1Net",label:"AYT Coğrafya-1"},{key:"aytHistory2Net",label:"AYT Tarih-2"},{key:"aytGeography2Net",label:"AYT Coğrafya-2"},{key:"aytPhilosophyNet",label:"AYT Felsefe"},{key:"aytReligionNet",label:"AYT Din"},{key:"foreignLanguageNet",label:"YDT"},
];
function selectedOption(program:ProgramDetail,year:number){const ranked=program.options.filter(option=>option.statistics.some(stat=>stat.year===year&&stat.successRank!==null)),candidates=ranked.length?ranked:program.options.filter(option=>option.statistics.some(stat=>stat.year===year));return(candidates.length?candidates:program.options).toSorted((a,b)=>{const rank=(option:AdmissionOption)=>option.statistics.find(stat=>stat.year===year)?.successRank??Number.MAX_SAFE_INTEGER;return rank(a)-rank(b);})[0];}
function comparison(entry:Entry,year:number){const program=entry.program;if(!program)return null;const option=selectedOption(program,year),stat=option?.statistics.find(item=>item.year===year),academic=program.academicDetails.find(item=>item.faculty===option?.faculty)??program.academicDetails[0],staff=academic?[academic.professorCount,academic.associateProfessorCount,academic.doctorFacultyMemberCount,academic.researchAssistantCount].reduce<number>((sum,value)=>sum+(value??0),0):null,net=option?.statistics.find(item=>item.year<=year&&netFields.some(field=>item[field.key]!==null));return{entry,program,option,stat,academic,staff:staff||null,net};}

export default async function Page({searchParams}:{searchParams:Promise<Params>}){
  const p=await searchParams,year=Math.min(2026,Math.max(2015,Number(p.year)||2026)),ids=[p.u1??p.left,p.u2??p.right,p.u3],programIds=[p.p1??p.leftProgram,p.p2??p.rightProgram,p.p3],entries=(await Promise.all(ids.map((id,index)=>side(id,programIds[index])))).filter((item):item is Entry=>item!==null),comparingPrograms=p.mode==="PROGRAM"||programIds.some(Boolean),results=entries.map(entry=>comparison(entry,year)).filter((item):item is NonNullable<ReturnType<typeof comparison>>=>item!==null),visibleNetFields=netFields.filter(field=>results.some(result=>result.net?.[field.key]!==null&&result.net?.[field.key]!==undefined));
  return <section className="content-section comparison-page"><header className="comparison-hero"><p className="eyebrow">Karar aracı</p><h1>{comparingPrograms?"Programları karşılaştır":"Üniversiteleri karşılaştır"}</h1><p className="lead">Seçenekleri aynı yılın verileriyle yan yana inceleyin.</p></header><CompareForm/>{results.length>=2&&<section className="comparison-results" aria-live="polite"><div className="comparison-heading"><p className="eyebrow">{year} karşılaştırması</p><h2>Sonuçlar</h2></div><div className="catalog-table-wrap comparison-table-wrap"><table className="catalog-table comparison-table"><caption>Temel program karşılaştırması</caption><thead><tr><th>Metrik</th>{results.map(result=><th key={result.program.summary.id}><span>{result.entry.university.name}</span><strong>{result.program.summary.name}</strong><small>{result.option?.faculty}</small></th>)}</tr></thead><tbody><tr><th>Başarı sırası</th>{results.map(result=><td key={result.program.summary.id}>{format(result.stat?.successRank)}</td>)}</tr><tr><th>Taban puan</th>{results.map(result=><td key={result.program.summary.id}>{format(result.stat?.minimumScore,3)}</td>)}</tr><tr><th>Kontenjan</th>{results.map(result=><td key={result.program.summary.id}>{format(result.stat?.quota)}</td>)}</tr><tr><th>Akademik kadro</th>{results.map(result=><td key={result.program.summary.id}>{format(result.staff)}</td>)}</tr><tr><th>Profesör</th>{results.map(result=><td key={result.program.summary.id}>{format(result.academic?.professorCount)}</td>)}</tr></tbody></table></div>{visibleNetFields.length>0&&<div className="catalog-table-wrap comparison-table-wrap"><table className="catalog-table comparison-table comparison-net-table"><caption>Programa son yerleşen öğrencinin diploma notu ve netleri</caption><thead><tr><th>Metrik</th>{results.map(result=><th key={result.program.summary.id}><span>{result.entry.university.name}</span><strong>{result.net?.year??"Veri yok"}</strong></th>)}</tr></thead><tbody>{visibleNetFields.map(field=><tr key={field.key}><th>{field.label}</th>{results.map(result=>{const value=result.net?.[field.key] as number|null|undefined;return <td key={result.program.summary.id}>{format(field.key==="averageSecondaryScore"&&value!=null?value/5:value,2)}</td>})}</tr>)}</tbody></table></div>}</section>}</section>;
}
