import {PageTitle} from "@/components/page-title";
import {CompareForm} from "@/components/compare-form";
import {getCatalogProgram,getUniversity,getUniversityCatalogStatistics,type AdmissionOption,type AdmissionStatistics,type ProgramDetail} from "@/lib/api/catalog";

export const metadata={title:"Üniversite veya program karşılaştır",description:"Programları aynı yıldaki başarı sırası, puan, kontenjan ve akademik kadroyla karşılaştır.",alternates:{canonical:"/karsilastir"}};
async function side(id?:string,programId?:string){if(!id)return null;try{return{university:await getUniversity(id),program:programId?await getCatalogProgram(programId):null};}catch{return null;}}
type Params={mode?:string;year?:string;u1?:string;u2?:string;u3?:string;p1?:string;p2?:string;p3?:string;left?:string;right?:string;leftProgram?:string;rightProgram?:string};
type Entry=NonNullable<Awaited<ReturnType<typeof side>>>;
const format=(value:number|null|undefined,digits=0)=>value?.toLocaleString("tr-TR",{maximumFractionDigits:digits})??"Veri yok";
const netFields:{key:keyof AdmissionStatistics;label:string}[]=[
  {key:"averageSecondaryScore",label:"Diploma notu"},{key:"tytTurkishNet",label:"TYT Türkçe"},{key:"tytSocialNet",label:"TYT Sosyal"},{key:"tytMathNet",label:"TYT Matematik"},{key:"tytScienceNet",label:"TYT Fen"},{key:"aytMathNet",label:"AYT Matematik"},{key:"aytPhysicsNet",label:"AYT Fizik"},{key:"aytChemistryNet",label:"AYT Kimya"},{key:"aytBiologyNet",label:"AYT Biyoloji"},{key:"aytLiteratureNet",label:"AYT Edebiyat"},{key:"aytHistory1Net",label:"AYT Tarih-1"},{key:"aytGeography1Net",label:"AYT Coğrafya-1"},{key:"aytHistory2Net",label:"AYT Tarih-2"},{key:"aytGeography2Net",label:"AYT Coğrafya-2"},{key:"aytPhilosophyNet",label:"AYT Felsefe"},{key:"aytReligionNet",label:"AYT Din"},{key:"foreignLanguageNet",label:"YDT"},
];
function selectedOption(program:ProgramDetail,year:number){const ranked=program.options.filter(option=>option.statistics.some(stat=>stat.year===year&&stat.successRank!==null)),candidates=ranked.length?ranked:program.options.filter(option=>option.statistics.some(stat=>stat.year===year));return(candidates.length?candidates:program.options).toSorted((a,b)=>{const rank=(option:AdmissionOption)=>option.statistics.find(stat=>stat.year===year)?.successRank??Number.MAX_SAFE_INTEGER;return rank(a)-rank(b);})[0];}
function comparison(entry:Entry,year:number){const program=entry.program;if(!program)return null;const option=selectedOption(program,year),stat=option?.statistics.find(item=>item.year===year),academic=program.academicDetails.find(item=>item.faculty===option?.faculty)??program.academicDetails[0],staff=academic?[academic.professorCount,academic.associateProfessorCount,academic.doctorFacultyMemberCount,academic.researchAssistantCount].reduce<number>((sum,value)=>sum+(value??0),0):null,net=option?.statistics.find(item=>item.year<=year&&netFields.some(field=>item[field.key]!==null));return{entry,program,option,stat,academic,staff:staff||null,net};}
type ComparisonResult=NonNullable<ReturnType<typeof comparison>>;
function ProgramComparisonTables({results,year,visibleNetFields}:{results:ComparisonResult[];year:number;visibleNetFields:typeof netFields}){
  const basicMetrics=[
    {label:"Başarı sırası",value:(result:ComparisonResult)=>format(result.stat?.successRank)},
    {label:"Taban puan",value:(result:ComparisonResult)=>format(result.stat?.minimumScore,3)},
    {label:"Kontenjan",value:(result:ComparisonResult)=>format(result.stat?.quota)},
    {label:"Akademik kadro",value:(result:ComparisonResult)=>format(result.staff)},
    {label:"Profesör",value:(result:ComparisonResult)=>format(result.academic?.professorCount)},
  ];
  return <section className="comparison-results" aria-live="polite"><div className="comparison-heading"><h2>Sonuçlar <small>({year} karşılaştırmaları)</small></h2></div>
    <div className="catalog-table-wrap comparison-table-wrap"><table className="catalog-table comparison-table comparison-transposed"><caption>Temel program karşılaştırması</caption><thead><tr><th scope="col">Üniversite / program</th>{basicMetrics.map(metric=><th scope="col" key={metric.label}>{metric.label}</th>)}</tr></thead><tbody>{results.map(result=><tr key={result.program.summary.id}><th scope="row"><strong>{result.entry.university.name}</strong><span>{result.program.summary.name}</span><small>{result.option?.faculty}</small></th>{basicMetrics.map(metric=><td key={metric.label}>{metric.value(result)}</td>)}</tr>)}</tbody></table></div>
    {visibleNetFields.length>0&&<div className="catalog-table-wrap comparison-table-wrap"><table className="catalog-table comparison-table comparison-net-table comparison-transposed"><caption>Programa son yerleşen öğrencinin diploma notu ve netleri</caption><thead><tr><th scope="col">Üniversite / program</th><th scope="col">Net yılı</th>{visibleNetFields.map(field=><th scope="col" key={field.key}>{field.label}</th>)}</tr></thead><tbody>{results.map(result=><tr key={result.program.summary.id}><th scope="row"><strong>{result.entry.university.name}</strong><span>{result.program.summary.name}</span></th><td>{result.net?.year??"Veri yok"}</td>{visibleNetFields.map(field=>{const value=result.net?.[field.key] as number|null|undefined;return <td key={field.key}>{format(field.key==="averageSecondaryScore"&&value!=null?value/5:value,2)}</td>})}</tr>)}</tbody></table></div>}
  </section>;
}

export default async function Page({searchParams}:{searchParams:Promise<Params>}){
  const p=await searchParams,year=Math.min(2026,Math.max(2015,Number(p.year)||2026)),ids=[p.u1??p.left,p.u2??p.right,p.u3],programIds=[p.p1??p.leftProgram,p.p2??p.rightProgram,p.p3],entries=(await Promise.all(ids.map((id,index)=>side(id,programIds[index])))).filter((item):item is Entry=>item!==null),comparingPrograms=p.mode==="PROGRAM"||programIds.some(Boolean),results=entries.map(entry=>comparison(entry,year)).filter((item):item is NonNullable<ReturnType<typeof comparison>>=>item!==null),universityResults=!comparingPrograms?await Promise.all(entries.map(async entry=>({entry,statistics:await getUniversityCatalogStatistics(entry.university.id).catch(()=>null)}))):[],visibleNetFields=netFields.filter(field=>results.some(result=>result.net?.[field.key]!==null&&result.net?.[field.key]!==undefined));
  return <section className="content-section comparison-page"><PageTitle help="İki veya üç üniversiteyi aynı yılın verileriyle karşılaştır. Üniversite + Program türünde her üniversitenin altından programını seç. Program karşılaştırmasında üniversite ve programlar satırlarda, ölçütler sütunlarda gösterilir.">Karşılaştır</PageTitle><CompareForm key={JSON.stringify(p)} initialMode={comparingPrograms?"PROGRAM":"UNIVERSITY"} initialYear={year} initialSelections={ids.map((id,index)=>({universityId:id??"",programId:programIds[index]??""}))}/>{!comparingPrograms&&universityResults.length>=2&&<section className="comparison-results" aria-live="polite"><div className="comparison-heading"><h2>Sonuçlar <small>({year} karşılaştırmaları)</small></h2></div><div className="catalog-table-wrap comparison-table-wrap"><table className="catalog-table"><caption>Üniversite karşılaştırması</caption><thead><tr><th>Ölçüt</th>{universityResults.map(({entry})=><th key={entry.university.id}>{entry.university.name}</th>)}</tr></thead><tbody>{[
    ['Program',(item:typeof universityResults[number])=>item.statistics?.programCount],
    ['Akademik birim',(item:typeof universityResults[number])=>item.statistics?.facultyCount],
    ['Tercih seçeneği',(item:typeof universityResults[number])=>item.statistics?.optionCount],
    ['Kontenjan',(item:typeof universityResults[number])=>item.statistics?.yearly.find(row=>row.year===year)?.quota],
    ['Yerleşen',(item:typeof universityResults[number])=>item.statistics?.yearly.find(row=>row.year===year)?.placed],
    ['Doluluk (%)',(item:typeof universityResults[number])=>item.statistics?.yearly.find(row=>row.year===year)?.fillRate],
  ].map(([label,value])=><tr key={String(label)}><th>{String(label)}</th>{universityResults.map(item=><td key={item.entry.university.id}>{format(typeof value==='function'?value(item):null,2)}</td>)}</tr>)}</tbody></table></div>{universityResults.some(item=>!item.statistics)&&<p role="alert">Bazı üniversitelerin verileri yüklenemedi. Tekrar denemek için sayfayı yenileyin.</p>}</section>}{results.length>=2&&<ProgramComparisonTables results={results} year={year} visibleNetFields={visibleNetFields} />}</section>;
}
